/**
 * CloudRail Client JavaScript Library v1.0.0
 * http://cloudrail.com
 * 
 * (c) 2014 licobo GmbH
 * 
 * @license
 * http://developer.cloudrail.com/license
 * 
 * Date: 2014-11-03T13:06Z
 */
var p=window,E=p.CloudRailClient||{},I=p.Math;E.Math={E:I.E,LN10:I.LN10,LN2:I.LN2,LOG10E:I.LOG10E,LOG2E:I.LOG2E,PI:I.PI,SQRT1_2:I.SQRT1_2,SQRT2:I.SQRT2,abs:I.abs,acos:I.acos,asin:I.asin,atan:I.atan,atan2:I.atan2,ceil:I.ceil,cos:I.cos,exp:I.exp,floor:I.floor,log:I.log,max:I.max,min:I.min,pow:I.pow,random:I.random,round:I.round,sin:I.sin,sqrt:I.sqrt,tan:I.tan};p.hasOwnProperty("CloudRailClient")||(p.CloudRailClient=E);var J=window,K=J.CloudRailClient||{};K.Date=J.Date;
J.hasOwnProperty("CloudRailClient")||(J.CloudRailClient=K);var R=window,S=R.CloudRailClient||{};S.Timer={};S.Timer.setTimeout=R.setTimeout;S.Timer.clearTimeout=R.clearTimeout;R.hasOwnProperty("CloudRailClient")||(R.CloudRailClient=S);
(function(e){var c=e.CloudRailClient||{},a=c.Uri=function(b){this.fragment=this.query=this.path=this.authority=this.scheme=null;void 0==b&&(b="");"object"==typeof b&&(b=b.toString());this.parse(b)};a.prototype.parse=function(b){if("string"!=typeof b&&!("object"==typeof b&&b instanceof String))throw Error("Uri.parse parameter is no string!");b=b.match(a.N);this.scheme=b[1]||null;this.authority=b[2]||null;this.path=b[3]||null;this.query=b[4]||null;this.fragment=b[5]||null;this.host=this.hostname=this.port=
this.userinfo=null;return this};a.prototype.getDefaultPort=function(){var b=this.scheme;if("string"!=typeof b&&!("object"==typeof b&&b instanceof String))return-1;b=b.toLowerCase();return void 0==a.A[b]?-1:a.A[b]};a.prototype.getHost=function(){if(null!=this.host)return this.host;if(null==this.authority)return null;var b=this.authority,d=b.indexOf("@");0<=d&&(b=b.substr(d+1));return this.host=b};a.prototype.getUserinfo=function(){if(null!=this.userinfo)return this.userinfo;if(null==this.authority)return null;
var b=this.authority,d=b.indexOf("@");0<=d&&(b=b.substr(0,d));return this.userinfo=b};a.prototype.getPort=function(){if(null!=this.port)return this.port;var b=null,d=this.getHost();if(null==d)return null;var g=d.indexOf(":");"["===d.charAt(0)?(b=d.indexOf("]"),b=Number.parseInt(d.substr(b+2))||null):g!==d.lastIndexOf(":")?b=null:0<=g&&(b=Number.parseInt(d.substr(g+1)));return this.port=b};a.prototype.getHostname=function(){if(null!=this.hostname)return this.hostname;var b="",b=this.getHost(),d=b.indexOf(":");
0>d||("["===b.charAt(0)?(d=b.indexOf("]"),b=b.substr(1,d-1)):b=d!==b.lastIndexOf(":")?b:b.substr(0,d));return this.hostname=b};a.prototype.getScheme=function(){return this.scheme};a.prototype.getAuthority=function(){return this.authority};a.prototype.getPath=function(){return this.path};a.prototype.getQuery=function(){return this.query};a.prototype.getFragment=function(){return this.fragment};a.prototype.getQueryParameter=function(b){var d={},g=this.query;if(null==g||"string"!=typeof g&&!("object"==
typeof g&&g instanceof String))return d;for(var g=g.split("&"),f=a.decodeQuery,h,c,e=0,m=g.length;e<m;++e)h=g[e].split("=",2),c=f(h[0],b),h=1<h.length?f(h[1],b):null,d[c]?d[c].push(h):d[c]=[h];return d};a.prototype.toString=function(){var b="";this.scheme&&(b+=this.scheme+":");this.authority&&(b+="//"+this.authority);this.path&&(b+=this.path);this.query&&(b+="?"+this.query);this.fragment&&(b+="#"+this.fragment);return b};a.N=/^(?:([^:\/?\#]+):)?(?:\/\/([^\/?\#]*))?([^?\#]*)(?:\?([^\#]*))?(?:\#(.*))?/;
a.A={ftp:"21",http:"80",https:"443",ws:"80",wss:"443"};a.parse=function(b){var d=new a;d.parse(b);return d};a.encodeComponent=function(b){return encodeURIComponent(b)};a.decodeComponent=function(b){return decodeURIComponent(b)};a.encode=function(b){return encodeURI(b)};a.decode=function(b){return decodeURI(b)};a.encodeQuery=function(b,d){void 0===d&&(d=!1);var g=encodeURIComponent(b+"");return d?g.replace(/%20/g,"+"):g};a.decodeQuery=function(b,d){void 0===d&&(d=!1);b+="";try{return decodeURIComponent(d?
b.replace(/\+/g,"%20"):b)}catch(g){return b}};a.prototype.splitQueryString=a.splitQueryString=function(b,d){var g={},f=b+"";if(null==f||"string"!=typeof f&&!("object"==typeof f&&f instanceof String))return g;for(var f=f.split("&"),h=a.decodeQuery,c,e,m=0,q=f.length;m<q;++m)c=f[m].split("=",2),e=h(c[0],d),c=1<c.length?h(c[1],d):null,g[e]?g[e].push(c):g[e]=[c];return g};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.LocalEvent=function(b){this.B=b;this.p=!1;this.i=null;a.n[b]=this};a.prototype.waitToFire=function(){for(var b=(new Date).valueOf();!this.p;)if((new Date).valueOf()>b+500&&(b=(new Date).valueOf(),e.localStorage["cr_"+this.B])){this.p=!0;break}e.localStorage.removeItem("cr_"+this.B)};a.prototype.addFireEventListener=function(b){this.i=b};a.prototype.C=function(b){this.p=!0;null!==this.i&&"function"==typeof this.i&&this.i.call({},b)};a.n={};a.fire=function(b,
d){var g=a.n;g[b]?g[b].C():(g=(new Date).valueOf()+9E5,e.localStorage.setItem("cr_"+b,JSON.stringify({expiry:g,param:d})))};a.eventStorageChange=function(b){var d=b.key;b=b.newValue;var g,f=3,h,c=a.n,k=(new Date).valueOf();if(!(d.length<f||0!==d.indexOf("cr_"))&&b){try{(g=JSON.parse(b))&&g.expiry&&g.expiry>k&&(h=d.substr(f),c[h]&&c[h].C(g.param))}catch(m){}e.localStorage.removeItem(d)}};a.init=function(){for(var b=e.localStorage,d="",g=0,a=b.length,h=3,c,k=(new Date).valueOf();g<a;++g)if(d=b.key(g),
!(d.length<h||0!==d.indexOf("cr_"))){try{if(c=JSON.parse(b[d]),c.expiry&&c.expiry>k)continue}catch(m){}b.removeItem(d)}};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c);e.addEventListener("storage",function(b){a.eventStorageChange(b)});a.init()})(window);
(function(e){function c(b,d,g,a){var f=n.f[b];void 0===f&&(f=n.f[b]={});f[d]=((f[d]|0)*g+a)/(g+1)}function a(b,d,g){var a=n.f[b];void 0===a&&(a=n.f[b]={});a[d]|=0;return a[d]+=g}function b(b,d,g,a,f,h){var c=n.e[b];void 0===c&&(c=n.e[b]={});void 0===(b=c[d])&&(b=c[d]={});void 0===(d=b[g])&&(d=b[g]={});d[a]=((d[a]|0)*f+h)/(f+1)}function d(b,d,g,a,f){var h=n.e[b];void 0===h&&(h=n.e[b]={});void 0===(b=h[d])&&(b=h[d]={});void 0===(d=b[g])&&(d=b[g]={});d[a]|=0;return d[a]+=f}function g(){if(!(0>n.a)){var b=
{client_id:x.t,session_id:x.G,version:x.VERSION,platform:x.PLATFORM,system:{browser:e.navigator.userAgent},init_time:n.r,stat_start_time:n.a,stat_last_time:n.c,time:(new Date).valueOf(),gateways:n.e,interfaces:n.f},d=new XMLHttpRequest;d.open("POST","https://root.cloudrail.com/gateway/");d.setRequestHeader("Content-Type","application/json");d.onreadystatechange=function(){2==d.readyState&&(200==d.status?(r(),t()):400<d.status&&599>=d.status&&q())};d.send(JSON.stringify(b))}}function f(){0>n.a||(q(),
g())}function h(){var b=(new Date).valueOf(),d=n.a;0<=d&&d+9E5<=b&&(l(),g())}function l(){n.s&&e.clearTimeout(n.s)}function k(){l();n.s=e.setTimeout(m,6E4)}function m(){0<n.q?k():g()}function q(){e.localStorage.cloudrail_stat=JSON.stringify({"init_time:":n.r,"stat_start_time:":n.a,"stat_last_time:":n.c,"gateways:":n.e,"interfaces:":n.f})}function r(){e.localStorage.removeItem("cloudrail_stat")}function B(b,d,g){for(var a=["request_count","error_count","warning_count"],f=0,h=a.length,c=d[a[0]],e=g[a[0]];f<
h;++f)b[a[f]]=d[a[f]]+g[a[f]];a=["average_request_length","average_response_length"];f=0;for(h=a.length;f<h;++f)b[a[f]]=(d[a[f]]*c+g[a[f]]*e)/(c+e)}function t(){n.s=null;n.r=(new Date).valueOf();n.a=-1;n.c=-1;n.e={};n.q=0;n.f={}}var x=e.CloudRailClient||{},n=x.Statistics=x.Statistics||{};t();var y=!1;n.updateRequest=function(g,a,f,c,e,l){h();var m=(new Date).valueOf();g=g.toLowerCase();e|=0;l|=0;++n.q;0>n.a&&(n.a=m);m>n.c&&(n.c=m);m=d(g,a,f,"request_count",1);b(g,a,f,"average_request_length",m-1,
c);d(g,a,f,"error_count",e);d(g,a,f,"warning_count",l);k()};n.updateResponse=function(g,a,f,c,e,l){h();var m=(new Date).valueOf();g=g.toLowerCase();e|=0;l|=0;--n.q;0>n.a&&(n.a=m);m>n.c&&(n.c=m);m=d(g,a,f,"response_count",1);b(g,a,f,"average_response_length",m-1,c);d(g,a,f,"error_count",e);d(g,a,f,"warning_count",l);k()};n.updateInterfaceRequest=function(b,d,g,f){h();var e=(new Date).valueOf();b=b.toLowerCase();g|=0;f|=0;0>n.a&&(n.a=e);e>n.c&&(n.c=e);e=a(b,"request_count",1);c(b,"average_request_length",
e-1,d);a(b,"error_count",g);a(b,"warning_count",f);k()};n.updateInterfaceResponse=function(b,d,g,f){h();var e=(new Date).valueOf();b=b.toLowerCase();g|=0;f|=0;0>n.a&&(n.a=e);e>n.c&&(n.c=e);e=a(b,"response_count",1);c(b,"average_response_length",e-1,d);a(b,"error_count",g);a(b,"warning_count",f);k()};var z=e.addEventListener;z("load",function(){if(null!==e.localStorage.getItem("cloudrail_stat")){var b=JSON.parse(e.localStorage.getItem("cloudrail_stat"));n.r=b.init_time;0<=b.stat_start_time&&(0>n.a||
n.a>b.stat_start_time)&&(n.a=b.stat_start_time);0<=b.stat_last_time&&(0>n.c||n.c<b.stat_last_time)&&(n.c=b.stat_last_time);var d=n.e,a=b.gateways;d||(d={});a||(a={});for(var f={},h=Object.keys(d),c=h.length,l=Object.keys(a),k=0,m;k<c;++k)if(m=h[k],void 0===a[m])f[m]=d[m];else{for(var x=m,z=d[m],w=a[m],y={},q=Object.keys(z),O=q.length,t=Object.keys(w),A=0,C=void 0,u=void 0,u=void 0;A<O;++A)if(u=q[A],void 0===w[u])y[u]=z[u];else{for(var C=u,F=z[u],D=w[u],G={},M=["create","read","update","delete"],v=
void 0,H=0,P=M.length;H<P;++H)if(v=M[H],void 0!==F[v]){var Q=v;if(void 0!==D[v]){var N={};B(N,F[v],D[v]);v=N}else v=F[v];G[Q]=v}else void 0!==D[v]&&(G[v]=D[v]);y[C]=G;u=t.indexOf(u);t.splice(u,1)}C=t.length;for(A=0;A<C;++A)u=t[A],y[u]=w[u];f[x]=y;m=l.indexOf(m);l.splice(m,1)}d=l.length;for(k=0;k<d;++k)m=l[k],f[m]=a[m];n.e=f;a=n.f;b=b.interfaces;a||(a={});b||(b={});f={};d=Object.keys(a);h=d.length;l=Object.keys(b);for(k=0;k<h;++k)c=d[k],void 0===b[c]?f[c]=a[c]:(f[c]={},B(f[c],a[c],b[c]),c=l.indexOf(c),
l.splice(c,1));a=l.length;for(k=0;k<a;++k)c=l[k],f[c]=b[c];n.f=f;r();g()}});z("unload",function(){y||(y=!0,f())});z("beforeunload",function(){y||(y=!0,f())});e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=x)})(window);
(function(e){var c=e.CloudRailClient||{},a=(c.IO=c.IO||{}).HttpHeaders=function(){this.b={};this.o={};this.D=",";this.contentType=null},b=a.ACCEPT="Accept",d=a.ACCEPT_CHARSET="Accept-Charset",g=a.ACCEPT_ENCODING="Accept-Encoding",f=a.ACCEPT_LANGUAGE="Accept-Language",h=a.ACCEPT_RANGES="Accept-Ranges",l=a.AGE="Age",k=a.ALLOW="Allow",m=a.AUTHORIZATION="Authorization",q=a.CACHE_CONTROL="Cache-Control",r=a.CONNECTION="Connection",B=a.CONTENT_ENCODING="Content-Encoding",t=a.CONTENT_LANGUAGE="Content-Language",
x=a.CONTENT_LENGTH="Content-Length",n=a.CONTENT_LOCATION="Content-Location",y=a.CONTENT_MD5="Content-MD5",z=a.CONTENT_RANGE="Content-Range",T=a.CONTENT_TYPE="Content-Type";a.COOKIE="Cookie";var U=a.DATE="Date",L=a.ETAG="ETag",V=a.EXPECT="Expect",s=a.EXPIRES="Expires",W=a.FROM="From",X=a.HOST="Host",Y=a.IF_MATCH="If-Match",Z=a.IF_MODIFIED_SINCE="If-Modified-Since",$=a.IF_NONE_MATCH="If-None-Match",aa=a.IF_RANGE="If-Range",w=a.IF_UNMODIFIED_SINCE="If-Unmodified-Since",ba=a.LAST_MODIFIED="Last-Modified",
ca=a.LOCATION="Location",O=a.MAX_FORWARDS="Max-Forwards",da=a.PRAGMA="Pragma",A=a.PROXY_AUTHENTICATE="Proxy-Authenticate",C=a.PROXY_AUTHORIZATION="Proxy-Authorization",u=a.RANGE="Range",F=a.REFERER="Referer",D=a.RETRY_AFTER="Retry-After",G=a.SERVER="Server";a.SET_COOKIE="Set-Cookie";var M=a.TE="TE",v=a.TRAILER="Trailer",H=a.TRANSFER_ENCODING="Transfer-Encoding",P=a.UPGRADE="Upgrade",Q=a.USER_AGENT="User-Agent",N=a.VARY="Vary",ea=a.VIA="Via",fa=a.WARNING="Warning",ga=a.WWW_AUTHENTICATE="WWW-Authenticate";
a.ENTITY_HEADERS=[k,B,t,x,n,y,z,T,s,ba];a.GENERAL_HEADERS=[q,r,U,da,v,H,P,ea,fa];a.REQUEST_HEADERS=[b,d,g,f,m,V,W,X,Y,Z,$,aa,w,O,C,u,F,M,Q];a.RESPONSE_HEADERS=[h,l,L,ca,A,D,G,N,ga];a.prototype.set=function(b,d){var g=b.toLowerCase();a.CONTENT_TYPE.toLowerCase();this.o[g]=b;this.b[g]=[d];return this};a.prototype.add=function(b,d){var g=b.toLowerCase();a.CONTENT_TYPE.toLowerCase();this.b[g]||(this.o[g]=b,this.b[g]=[]);this.b[g].push(d);return this};a.prototype.forEach=function(b){for(var d in this.b)"function"==
typeof b&&b.call(this,d,this.value(d));return this};a.prototype.remove=function(b,d){var g=b.toLowerCase();if(this.b[g]){var a=this.b[g],f=a.indexOf(d);0<=f&&(this.b[g]=a.slice(0,f).concat(a.slice(f+1,a.length)));return this}};a.prototype.removeAll=function(b){b=b.toLowerCase();if(this.b[b])return delete this.b[b],this};a.prototype.value=function(b){b=b.toLowerCase();return this.b[b]?this.b[b].join(this.D):null};a.prototype.parse=function(b){if("string"!==typeof b)if("object"===typeof b&&b.toString)b=
b.toString();else throw Error("HttpHeaders.parse input is no string or can't convert to string!");b=b.replace(/\r/g,"").split("\n");for(var d=/^\s+/,g=0,a=b.length,f,h,c,e;g<a;++g)if(!(0>=b[g].length)&&(f=b[g].split(":"),h=f.shift(),f=f.join(":"),h&&""!=h&&""!=f))for(f=f.replace(d,""),f=f.split(this.D),e=f.length,c=0;c<e;++c)this.add(h,f[c]);return this};a.prototype.toString=function(){var b="",d;for(d in this.b)b+=this.o[d]+": "+this.value(d)+"\n";return b};a.parse=function(b){var d=new a;d.parse(b);
return d};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){function c(){var b=d.getArrayBuffer(32);return a.Converter.ArrayBuffer.toBase64Url(b)}var a=e.CloudRailClient||{},b=a.Crypto=a.Crypto||{},d=b.Random=b.Random||{},g=(a.IO=a.IO||{}).LocalUriCallback=function(b){this.w=b};g.prototype.getBaseUri=function(){return a.Config.LocalUriCallback.getBaseUri()};g.prototype.addToken=function(b){var d=g.v.push(b)-1;g.J[d]=this.w;d=e.document.location.toString();0<=d.search(b)&&this.w(d)};g._createToken=c;g.prototype.createUriToken=function(){var b=
c();this.addToken(b);return b};g.v=[];g.J=[];g.isOpen=function(b){"string"==typeof b||"object"!=typeof b||b instanceof String||(b=b.toString());for(var d=g.v,a=0,c=g.v.length;a<c;++a)if(0<=b.search(d[a]))g.J[a](b)};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=a);e.addEventListener("hashchange",function(){g.isOpen(e.document.location.toString())});e.addEventListener("load",function(){g.isOpen(e.document.location.toString())})})(window);
(function(e){var c=e.CloudRailClient||{},a=c.IO=c.IO||{},b=c.Statistics=c.Statistics||{},d=a.HttpClient=function(){this.g=e.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");this.onDone=this.onLoading=this.onHeadersReceived=null;this.status=0;this.statusText="";this.request=new a.HttpClientRequest;this.response=new a.HttpClientResponse};d.Methods={GET:"GET",POST:"POST",HEAD:"HEAD",PUT:"PUT",DELETE:"DELETE",TRACE:"TRACE",OPTIONS:"OPTIONS",CONNECT:"CONNECT",PATCH:"PATCH"};d.prototype.Methods=
d.Methods;d.prototype.addCredentials=function(){};d.prototype.close=function(){return this};d.prototype.open=function(b,d,a,c,e){var m;void 0===a&&(a=80);m="http";443==a&&(m="https");this.l=d=m+"://"+d+":"+a+c;this.g.open(b,d);this.g.responseType="blob";if(e){if("function"!=typeof e)throw Error("HttpClient.open call is no function");this.onDone=e}return this};d.prototype.openUrl=function(b,d){"string"!=typeof d&&(d=d.toString());this.l=d;this.g.open(b,d,!0);this.g.responseType="blob";return this};
d.prototype.setResponseType=function(b){var d="blob";switch(b){case "arraybuffer":d="arraybuffer";break;case "text":d="text";break;case "blob":d="blob";break;default:throw Error("HttpClient setResponseType bad type error: '"+b+"'");}this.g.responseType=d};d.prototype.send=function(){var d=this.g,a=0;this.l&&this.l.length&&(a+=this.l.length);this.request.headers.forEach(function(b,c){d.setRequestHeader(b,c);a+=b.length+c.length+3});d.onreadystatechange=function(a){return function(){a.status=d.status;
a.statusText=d.statusText;2==d.readyState&&(a.response.headers.parse(d.getAllResponseHeaders()),"function"==typeof a.onHeadersReceived&&a.onHeadersReceived.call(a,a));3==d.readyState&&"function"==typeof a.onLoading&&a.onLoading.call(a,a);4==d.readyState&&(a.response.data=d.response,"function"==typeof a.onDone&&a.onDone.call(a,a),b.updateInterfaceResponse("http",d.response.size|d.response.length|d.response.byteLength|0))}}(this);this.request.data?(d.send(this.request.data),a+=this.request.data.size|
this.request.data.length|this.request.data.byteLength|0):d.send();b.updateInterfaceRequest("http",a);return this};(a.HttpClientRequest=function(){this.headers=new a.HttpHeaders;this.data=null}).prototype.write=function(){};(a.HttpClientResponse=function(){this.headers=new a.HttpHeaders;this.data=null}).prototype.getDataBlob=function(){return"object"==typeof this.data&&this.data instanceof Blob?this.data:new Blob([this.data])};d=a.ContentType=function(){};d.prototype={};d.parse=function(b){if("string"!==
typeof b&&("object"!==typeof b||!b.toString))throw Error("HttpHeaders.parse input is no string or can't convert to string!");};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);(function(e){var c=e.CloudRailClient||{};((c.IO=c.IO||{}).UriCall=function(a){this.M=a}).prototype.open=function(){e.open(this.M,"_blank")};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.Converter=c.Converter||{},a=a.ArrayBuffer=a.ArrayBuffer||{};a.change32BitByteEndian=function(b){var d=new Uint8Array(b),a=Math.floor(b.byteLength/4),f=new ArrayBuffer(4*a),h=new Uint8Array(f);for(b=0;b<a;++b)h[4*b+3]=d[4*b+0],h[4*b+2]=d[4*b+1],h[4*b+1]=d[4*b+2],h[4*b+0]=d[4*b+3];return f};a.toHex=function(b,d){for(var a="",f=new Uint8Array(b),h,c=0;c<f.length;++c)h=f[c],a+="0123456789abcdef".charAt(h>>4&15),a+="0123456789abcdef".charAt(h&15);!0===d&&(a=
a.toUpperCase());return a};a.fromHex=function(b){"0x"==b.slice(0,2)&&(b=b.slice(2));var d=Math.ceil(b.length/2);0<(b.length&1)&&(b="0"+b);for(var a=new ArrayBuffer(d),f=new Uint8Array(a),h=0;h<d;++h){var c=b.slice(2*h,2*h+2);f[h]=parseInt(c,16)}return a};a.toBin=function(b){var d="";b=new Uint8Array(b);for(var a,f=0;f<b.length;++f)a=b[f],d+=a&1,d+=a>>1&1,d+=a>>2&1,d+=a>>3&1,d+=a>>4&1,d+=a>>5&1,d+=a>>6&1,d+=a>>7&1;return d};a.toBase64=function(b,d){function a(b){return"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(b)}
var f="",h=new Uint8Array(b),c,e;"undefined"===typeof d&&(d="=");for(e=0;e<h.length;e+=3)f+=a(h[e]>>2&63),e+2<h.length?(c=(h[e]&3)<<4|h[e+1]>>4,f+=a(c&63),c=(h[e+1]&15)<<2|h[e+2]>>6,f+=a(c&63),f+=a(h[e+2]&63)):(e+1<h.length?(c=(h[e]&3)<<4|h[e+1]>>4,f+=a(c&63),c=(h[e+1]&15)<<2,f+=a(c&63)):(c=(h[e]&3)<<4,f+=a(c&63),f+=d),f+=d);return f};a.fromBase64=function(b){if("string"!=typeof b&&!("object"==typeof b&&b instanceof String))throw Error("ArrayBuffer.fromBase64 fail: input is no string");b=b.replace(/[^A-Za-z0-9\+\/]/g,
"");var d=b.length,a=3*Math.floor(b.length/4),f=b.length%4,c,e,k,m=0,q=0;2===f?a+=1:3===f&&(a+=2);for(var r=new Uint8Array(a),f=0;f<d;++f)if(e=f&3,c=b.charCodeAt(f),k=0,64<c&&91>c?k=c-65:96<c&&123>c?k=c-71:47<c&&58>c?k=c+4:43===c?k=62:47===c&&(k=63),m|=k<<18-6*e,3===e||1===d-f){for(c=0;3>c&&q<a;c++)r[q++]=m>>>(16>>>c&24)&255;m=0}return r.buffer};a.toBase64Url=function(b,d){function a(b){return"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b)}var f="",c=new Uint8Array(b),
e,k;"undefined"===typeof d&&(d="");for(k=0;k<c.length;k+=3)f+=a(c[k]>>2&63),k+2<c.length?(e=(c[k]&3)<<4|c[k+1]>>4,f+=a(e&63),e=(c[k+1]&15)<<2|c[k+2]>>6,f+=a(e&63),f+=a(c[k+2]&63)):(k+1<c.length?(e=(c[k]&3)<<4|c[k+1]>>4,f+=a(e&63),e=(c[k+1]&15)<<2,f+=a(e&63)):(e=(c[k]&3)<<4,f+=a(e&63),f+=d),f+=d);return f};a.fromBase64Url=function(b){b=b.replace(/[^A-Za-z0-9\-_]/g,"");var d=b.length,a=3*Math.floor(b.length/4),f=b.length%4,c,e,k,m=0,q=0;2===f?a+=1:3===f&&(a+=2);for(var r=new Uint8Array(a),f=0;f<d;++f)if(e=
f&3,c=b.charCodeAt(f),k=0,64<c&&91>c?k=c-65:96<c&&123>c?k=c-71:47<c&&58>c?k=c+4:43===c?k=62:47===c&&(k=63),m|=k<<18-6*e,3===e||1===d-f){for(c=0;3>c&&q<a;c++)r[q++]=m>>>(16>>>c&24)&255;m=0}return r.buffer};a.toBase=function(b,d){if(36<d)throw new RangeError("Min base is 2.");if(2>d)throw new RangeError("Max base is 36.");if(!(b instanceof ArrayBuffer)||0>=b.length)throw new TypeError("bad first argument or length");var a="",c,e=Math.log(d)/Math.LN2,l=Math.floor(e);if(e==l)for(var k=4294967295>>>32-
l,m=new BitArray(b),e=Math.ceil(m.length/l)-1;0<=e;--e){try{c=m.getUint8(e*l)&k}catch(q){c=m.getUint8(m.length-8),c=c>>>e*l-m.length+8&k}if(0<c||0<a.length||0==e)a+="0123456789abcdefghijklmnopqrstuvwxyz".charAt(c)}else{c=new Uint8Array(b.byteLength);c.set(new Uint8Array(b));for(var l=b.byteLength,k=new Uint8Array(Math.ceil(8*b.byteLength/e)),m=0,r;0<l;){r=0;for(e=l-1;0<=e;--e)r=c[e]+256*r,c[e]=Math.floor(r/d),r%=d,e==l-1&&0>=c[e]&&--l;k[m++]=r}for(e=m-1;0<=e;--e)a+="0123456789abcdefghijklmnopqrstuvwxyz".charAt(k[e])}return a};
a.toWString=function(b){return String.fromCharCode.apply(null,new Uint16Array(b))};a.concat=function(){var b,d=0,a=[];for(b=0;b<arguments.length;++b)arguments[b]instanceof ArrayBuffer&&(d+=arguments[b].byteLength,a.push(arguments[b]));var d=new ArrayBuffer(d),c=new Uint8Array(d),e=0;for(b=0;b<a.length;++b)c.set(new Uint8Array(a[b]),e),e+=a[b].byteLength;return d};a.slice=function(b,a,c){if(c>b.byteLength||a>b.byteLength||0>c||0>a)throw new RangeError("Index too large.");if(a>c)throw new RangeError("End must > start");
if(b.slice)return b.slice(a,c);var f=new ArrayBuffer(c-a);(new Uint8Array(f)).set((new Uint8Array(b)).subarray(a,c));return f};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.Converter=c.Converter||{},a=a.String=a.String||{};a.toArrayBuffer=function(b){for(var a=new ArrayBuffer(b.length),c=new Uint8Array(a),f=0,e=b.length;f<e;f++)c[f]=b.charCodeAt(f)&255;return a};a.toUtf8CodedUint8Array=function(b){var a=new Uint8Array(3*b.length),c=0,f=b.length,e,l;for(e=0;e<f;++e)l=b.charCodeAt(e),128>l?a[c++]=l:(2048>l?a[c++]=192|l>>>6:(a[c++]=224|l>>>12,a[c++]=128|l>>>6&63),a[c++]=128|l&63);return new Uint8Array(a.buffer.slice(0,c))};a.fromUint8Array=
function(b){for(var a=new String,c=0,f=b.length;c<f;)a+=String.fromCharCode(b[c++]);return a};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.Converter=c.Converter||{},a=a.Utf8String=a.Utf8String||{};a.toUint32Array=function(b){for(var a=new Uint32Array(b.length),c=0,f=0,e,l,k,m,q=b.length;c<q;)e=b.charCodeAt(c),127>e?(a[f++]=e,c++):191<e&&224>e?(l=b.charCodeAt(c+1),a[f++]=(e&31)<<6|l&63,c+=2):191<e&&240>e?(l=b.charCodeAt(c+1),k=b.charCodeAt(c+2),a[f++]=(e&15)<<12|(l&63)<<6|k&63,c+=3):(l=b.charCodeAt(c+1),k=b.charCodeAt(c+2),m=b.charCodeAt(c+3),a[f++]=(e&7)<<18|(l&63)<<12|(k&63)<<6|m&63,c+=4);
return a};a.toUint16Array=function(b){for(var a=new Uint16Array(b.length),c=0,f=0,e,l,k,m=b.length;c<m;)e=b.charCodeAt(c),127>e?(a[f++]=e,c++):191<e&&224>e?(l=b.charCodeAt(c+1),a[f++]=(e&31)<<6|l&63,c+=2):(l=b.charCodeAt(c+1),k=b.charCodeAt(c+2),a[f++]=(e&15)<<12|(l&63)<<6|k&63,c+=3);return a};a.toUint8Array=function(b){for(var a=new Uint8Array(b.length),c=0,f=0,e,l,k=b.length;c<k;)e=b.charCodeAt(c),127>e?(a[f++]=e,c++):191<e&&224>e?(l=b.charCodeAt(c+1),a[f++]=(e&31)<<6|l&63,c+=2):(l=b.charCodeAt(c+
1),e=b.charCodeAt(c+2),a[f++]=(l&3)<<6|e&63,c+=3);return a};a.fromUint8Array=function(b){for(;c<e;)a+=String.fromCharCode(b[c++]);for(var a="",c=0,e=b.length,h,l,k;c<e;)h=b[c],127>h?(a+=String.fromCharCode(h),c++):191<h&&224>h&&c+1<e?(l=b[c+1],a+=String.fromCharCode((h&31)<<6|l&63),c+=2):223<h&&240>h&&c+2<e?(l=b[c+1],k=b[c+2],a+=String.fromCharCode((h&15)<<12|(l&63)<<6|k&63),c+=3):c+3<e?(l=b[c+1],k=b[c+2],a+=String.fromCharCode((h&7)<<18|(l&63)<<12|(k&63)<<6|b[c+3]&63),c+=3):c++;return a};a.encode=
function(a){if(unescape&&encodeURIComponent)return unescape(encodeURIComponent(a));for(var d="",c=0,e,h=a.length,c=0;c<h;++c)e=a.charCodeAt(c),128>e?d+=String.fromCharCode(e):(2048>e?d+=String.fromCharCode(192|e>>>6):(d+=String.fromCharCode(224|e>>>12),d+=String.fromCharCode(128|e>>>6&63)),d+=String.fromCharCode(128|e&63));return d};a.decode=function(a){if(escape&&decodeURIComponent)try{return decodeURIComponent(escape(a))}catch(d){}for(var c="",e=0,h=a.length,l,k,m;e<h;)l=a.charCodeAt(e),127>l?(c+=
String.fromCharCode(l),e++):191<l&&224>l&&e+1<h?(k=a.charCodeAt(e+1),c+=String.fromCharCode((l&31)<<6|k&63),e+=2):223<l&&240>l&&e+2<h?(k=a.charCodeAt(e+1),m=a.charCodeAt(e+2),c+=String.fromCharCode((l&15)<<12|(k&63)<<6|m&63),e+=3):e+3<h?(k=a.charCodeAt(e+1),m=a.charCodeAt(e+2),c+=String.fromCharCode((l&7)<<18|(k&63)<<12|(m&63)<<6|a.charCodeAt(e+3)&63),e+=3):e++;return c};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.Crypto=c.Crypto||{};(a.Random=a.Random||{}).getArrayBuffer=function(a){a=new Uint8Array(a);var d=e.crypto|e.msCrypto|0;if(d&&d.getRandomValues)d.getRandomValues(a);else for(var d=(new Date).getTime(),c=0,f=a.length;c<f;++c)a[c]=(d+256*Math.random())%256|0,d=Math.floor(d/16);return a.buffer};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{};((c.Storage=c.Storage||{}).SandboxCache=function(){}).prototype={};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{},b=c.NodeIdentifier=function(a,b,c){this._object_type=a;this._identifier_service_tag=b;this._identifier_service_data=c||{};this._data_match=this._data_selection=null};b.prototype={};b.prototype.getType=function(){return this._object_type};b.prototype.getServiceTag=function(){return this._identifier_service_tag};b.prototype.read=function(b,c){return a.read(this,b,c)};b.prototype.remove=function(b,c){return a.remove(this,
b,c)};b.prototype.getServiceTag=function(){return this._identifier_service_tag};b.prototype.getByteLength=function(){return 0};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{},b=c.NodeIdentifier,d=c.Node=function(a,b,d){c.NodeIdentifier.call(this,a,b,d)};d.prototype=new b;d.prototype.constructor=d;d.prototype._selectData=function(a,b,c){"undefined"===typeof c&&(c=!0);c?(this._data_selection||(this._data_selection=[]),this._data_selection.push(b)):(this._data_selection||(this._data_selection=a.AVAILABLE_ENTRYS),a=this._data_selection.indexOf(b),0<=a&&this._data_selection.splice(a,1))};
d.prototype.selectAll=function(){this._data_selection=d.AVAILABLE_ENTRYS;return this};d.prototype.selectNone=function(){this._data_selection=[];return this};d.prototype.create=function(b,c){return a.create(this,b,c)};d.prototype.update=function(b,c){return a.update(this,b,c)};d.prototype.getByteLength=function(){return b.prototype.getByteLength.call(this)};d.AVAILABLE_ENTRYS=[];d.DEFAULT_ENTRYS=d.AVAILABLE_ENTRYS;d.byIdentifier=function(a){var b=new d,e=c.CloudRailInterface.ObjectType;switch(a._object_type){case e.IDENTITY:b=
new c.Identity;break;case e.CLIENT_IDENTITY:b=new c.ClientIdentity;break;case e.USER_IDENTITY:b=new c.UserIdentity;break;case e.USER_ACCOUNT_INFO:b=new c.UserAccountInfo;break;case e.FILE_STORAGE:b=new c.FileStorage;break;case e.FILE:b=new c.File;break;case e.THUMBNAIL:b=new c.Thumbnail;break;default:return b}b._object_type=a._object_type;b._identifier_service_tag=a._identifier_service_tag;b._identifier_service_data=a._identifier_service_data;b._data_selection=a._data_selection;b._data_match=a._data_match;
return b};e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).IDENTITY="CloudRail.Identity";var b=c.Identity=function(a,e,f){c.Node.call(this,b.ObjectType,a,e);this._access_authorizations=f};b.prototype=new c.Node;b.ObjectType=c.CloudRailInterface.ObjectType.IDENTITY;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).CLIENT_IDENTITY="CloudRail.Identity.Client";var b=c.ClientIdentity=function(a,e){c.Identity.call(this,a,e);this._object_type=b.ObjectType};b.prototype=new c.Identity;b.ObjectType=c.CloudRailInterface.ObjectType.CLIENT_IDENTITY;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).USER_IDENTITY="CloudRail.Identity.User";var b=c.UserIdentity=function(a,e){c.Identity.call(this,a,e);this._object_type=b.ObjectType};b.prototype=new c.Identity;b.ObjectType=c.CloudRailInterface.ObjectType.USER_IDENTITY;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).USER_ACCOUNT_INFO="CloudRail.User.Account.Info";var b=c.UserAccountInfo=function(a,e){c.Node.call(this,b.ObjectType,a,e)};b.prototype=new c.Node;b.prototype.selectDisplayName=function(a){this._selectData(b,"sDisplayName",a);return this};b.prototype.selectCountry=function(a){this._selectData(b,"sCountry",a);return this};b.prototype.selectEmail=function(a){this._selectData(b,"sEmail",
a);return this};b.prototype.selectAll=function(){this._data_selection=b.AVAILABLE_ENTRYS;return this};b.prototype.selectNone=function(){this._data_selection=[];return this};b.ObjectType=c.CloudRailInterface.ObjectType.USER_ACCOUNT_INFO;b.AVAILABLE_ENTRYS=["sDisplayName","sCountry","sEmail"];b.DEFAULT_ENTRYS=b.AVAILABLE_ENTRYS;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).FILE_STORAGE="CloudRail.FileStorage";var b=c.FileStorage=function(a,e){c.Node.call(this,b.ObjectType,a,e)};b.prototype=new c.Node;b.ObjectType=c.CloudRailInterface.ObjectType.FILE_STORAGE;b.AVAILABLE_ENTRYS=["lTotalSpace","lUsageSpace"];b.DEFAULT_ENTRYS=b.AVAILABLE_ENTRYS;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.Node,b=c.CloudRailInterface=c.CloudRailInterface||{};(b.ObjectType=b.ObjectType||{}).FILE="CloudRail.File";var d=c.File=function(a,b){c.Node.call(this,d.ObjectType,a,b)};d.prototype=new a;d.prototype.selectFilename=function(a){this._selectData(d,"sFilename",a);return this};d.prototype.selectMimeType=function(a){this._selectData(d,"sMimeType",a);return this};d.prototype.selectStreamData=function(a){this._selectData(d,"bStreamData",a);return this};d.prototype.selectStreamSize=
function(a){this._selectData(d,"lStreamSize",a);return this};d.prototype.selectStreamHashs=function(a){this._selectData(d,"lssStreamHashs",a);return this};d.prototype.selectChilds=function(a){this._selectData(d,"aniChilds",a);return this};d.prototype.selectChildsHashs=function(a){this._selectData(d,"lssChildsHashs",a);return this};d.prototype.selectParents=function(a){this._selectData(d,"aniParents",a);return this};d.prototype.selectCreateTimestamp=function(a){this._selectData(d,"lCreateTimestamp",
a);return this};d.prototype.selectLastModificationTimestamp=function(a){this._selectData(d,"lLastModificationTimestamp",a);return this};d.prototype.selectMetaOnly=function(){this._data_selection="sFilename sMimeType lStreamSize lssStreamHashs lssChildsHashs aniParents lCreateTimestamp lLastModificationTimestamp".split(" ");return this};d.prototype.selectAll=function(){this._data_selection=d.AVAILABLE_ENTRYS;return this};d.prototype.selectNone=function(){this._data_selection=[];return this};d.prototype.getByteLength=
function(){return a.prototype.getByteLength.call(this)};d.ObjectType=c.CloudRailInterface.ObjectType.FILE;d.AVAILABLE_ENTRYS="sFilename sMimeType bStreamData lStreamSize lssStreamHashs aniChilds lssChildsHashs aniParents lCreateTimestamp lLastModificationTimestamp".split(" ");d.DEFAULT_ENTRYS="sFilename sMimeType lStreamSize lssStreamHashs aniChilds lssChildsHashs aniParents lCreateTimestamp lLastModificationTimestamp".split(" ");e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{};(a.ObjectType=a.ObjectType||{}).THUMBNAIL="CloudRail.Thumbnail";var b=c.Thumbnail=function(a,e){c.Node.call(this,b.ObjectType,a,e)};b.prototype=new c.Node;b.prototype.selectFile=function(a){this._selectData(File,"niFile",a);return this};b.prototype.selectWidth=function(a){this._selectData(File,"lWidth",a);return this};b.prototype.selectHeight=function(a){this._selectData(File,"lHeight",a);return this};b.prototype.selectMimeType=
function(a){this._selectData(File,"sMimeType",a);return this};b.prototype.selectStreamData=function(a){this._selectData(File,"bStreamData",a);return this};b.prototype.selectStreamSize=function(a){this._selectData(File,"lStreamSize",a);return this};b.prototype.selectMetaOnly=function(){this._data_selection=["niFile","lWidth","lHeight","sMimeType"];return this};b.prototype.selectAll=function(){this._data_selection=b.AVAILABLE_ENTRYS;return this};b.prototype.selectNone=function(){this._data_selection=
[];return this};b.ObjectType=c.CloudRailInterface.ObjectType.THUMBNAIL;b.AVAILABLE_ENTRYS="niFile lWidth lHeight sMimeType bStreamData lStreamSize".split(" ");b.DEFAULT_ENTRYS=b.AVAILABLE_ENTRYS;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=(c.CloudRailInterface=c.CloudRailInterface||{}).InterfaceResponse=function(a,c){this.L=a||0;"undefined"==typeof c&&(c=[]);"object"==typeof c&&c instanceof Array||(c=[c]);this.k=c};a.prototype.getStatus=function(){return this.L};a.prototype.addResult=function(a){this.k.push(a)};a.prototype.getResults=function(){return this.k};a.prototype.getResultsByteLength=function(){for(var a=0,c=0,e=this.k.length|0;c<e;++c)a+=this.k[c].getByteLength();return a};e.hasOwnProperty("CloudRailClient")||
(e.CloudRailClient=c)})(window);
(function(e){var c=e.CloudRailClient||{},a=c.CloudRailInterface=c.CloudRailInterface||{},b=c.NodeIdentifier=c.NodeIdentifier||{},d=c.Converter=c.Converter||{},g=d.ArrayBuffer=d.ArrayBuffer||{},f=c.Statistics=c.Statistics||{},h=c.Crypto=c.Crypto||{},l=h.Hash=h.Hash||{},d=a.InterfaceFunction=a.InterfaceFunction||{},k=d.CREATE="create",m=d.READ="read",q=d.UPDATE="update",r=d.DELETE="delete";a.u=a.u||[];var B=a.ObjectTypeInterface=function(){this.d={}};B.prototype.createInterfaceFunction=function(a,b){this.d[a]=
b;return this};var t=a.Service=function(a){this.I=a;this.h={}};t.prototype.createObjectTypeInterface=function(a){var b=new B(a);return this.h[a]=b};a.createService=function(b){b=new t(b);a.u.push(b);return b};d=a.ServiceInstance=function(a,b){this.H=a;this.F=b};d.prototype.getService=function(){return this.H};d.prototype.getOptions=function(){return this.F};d.prototype.read=function(b,c,d){a.read(b,this.F,this.H,c,d)};a.getService=function(b,d){function e(a,c,d){if(0>=d.length)throw Error("Gateway is invalid!");
var h=d.shift(),n=h[0],l=g.toHex(g.fromBase64(h[1])),w=new XMLHttpRequest;w.open("GET","https://root.cloudrail.com/certificate/"+n);w.onreadystatechange=function(){if(4==w.readyState)if(200==w.status){var h=w.response,n=!1,s=new L;s.setPublicCert("-----BEGIN CERTIFICATE-----\nMIIEqTCCApGgAwIBAgIBCjANBgkqhkiG9w0BAQsFADBXMQswCQYDVQQGEwJERTEU\nMBIGA1UECgwLbGljb2JvIEdtYkgxMjAwBgNVBAMMKUNsb3VkUmFpbCBQcmltYXJ5\nIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTE0MDkyMjE0MzMxMVoXDTE5MDky\nMTE0MzMxMVowTzELMAkGA1UEBhMCREUxFDASBgNVBAoMC2xpY29ibyBHbWJIMSow\nKAYDVQQDDCFDbG91ZFJhaWwgR2F0ZXdheSBDQSBJbnRlcm1lZGlhdGUwggEiMA0G\nCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9nUqge8uj64bGpiklkl1UkNihvtmI\nuCOMEWItcZamtkHzvWoScgpioxWB+Pz7MKh9+k5wLdyhAZd18xgFCjwuvDsDgHm6\nBPKL4zBPCOWhiL8JF6RiE0t8/MY05UXZ64oF7PVojvXV8L+uo38yzILILo+gaBeX\nt75NcVkHxQTU3nbKKGfVGlzb5VetzEAZhDikAr3Gx1bAky+LhLai7YGXAvkR0DSp\nv7mnwir0BKQK//hOozhAgrjLBtzFLLMgQFmOqX9L1RGFyXfTvqNvgfjZ1slluCYf\nwoVDFr603Iyqbft4+35oTzlog9GlyXS8bkPjh0Sqs69B8of9LjCP2dl7AgMBAAGj\ngYcwgYQwHQYDVR0OBBYEFJLUlGe29cOKjDH1MfvFw9apBCTkMB8GA1UdIwQYMBaA\nFK6uj2/7tlXyv4+qplcufnKoB0JjMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgEm\nMCcGA1UdJQQgMB4GCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMwDQYJKoZI\nhvcNAQELBQADggIBAAHgBI4yrYR7GC2syexg6Q5Bj3juaMyf0iAfM/CiGFAUnbNT\nw971ViZqeN2b3qgX/V3i29wgNK6rARRA2AqOafZKzSqWy4Uqi5etnDNgRsW5Wnri\nWxGCII+mvtVgdW6ifNlUSMS5zyZ34o/c0z+lHcZGH6QbJVSAoPlE+JWh3dqV0VQN\nyOXXjDfUV2ClSqVHjCGFtG4yFja1Q96gbhwdceVd8Xo3Ms4UA0cssClSoG0+idOr\n50HWNKyQvfyCYJnoy5q9c4x6BWnv5hkYxMi/RofWNHTAHGNvPYT8gWCU2atlysgw\nshYD1RJGAkEtC7aszZ8mZN+TsoYbOuDw2JXtZVIBmowvw0NrQDgPXhFfBISmyDWG\nQERj77UQ0rEueboFu/bsKYDQ8BrydEg2pHBqrStGv5ODLGfALJQte+sadqCRp20l\nY+wsOk0AHFx6yZNMSgh20MjR5m+pqwW5HT/snqZEy45Mkaf29TBgHWnOmPgOp/aE\nsVa4dSulAS7FJHFtNL3aASAev478tsbpHHPxImt8RBCbpQRW5Q2/Bpv6+vxslU8P\n97xJ4bQXja8UBbW7573dMtUToRW+WUtBPy7bgcz4ENZZwXlz2o2hHbQs8iGsAJ+O\nZe3KDyV3QBDD9pk/b8eHtW3wao3bauPFQk2PJrgTA9azmz02o7bktePHRtA6\n-----END CERTIFICATE-----");
s.verifyPublicCertSign(h)&&(s=new L,s.setPublicCert(h),h=s.verificationSign(l),s=g.toHex(q.hash(a)),h===s&&(n=!0));if(n)for(eval(a),m=f.length,k=0;k<m;++k){if(f[k].I==b){c&&c(f[k]);break}}else e(a,c,d)}else{if(401==w.status)throw Error("Unauthorized! Client ID invalid?");throw Error("Gateway is invalid!");}};w.send()}for(var f=a.u,k=0,m=f.length;k<m;++k)if(f[k].I==b){d&&d(f[k]);return}var L=h.JSEncrypt,q=l.SHA256,s=new XMLHttpRequest;s.open("GET","https://root.cloudrail.com/gateway/"+b.toLowerCase()+
"?clientid="+c.t+"&sessionid="+c.G);s.onreadystatechange=function(){if(4==s.readyState)if(200==s.status){var a=s.getResponseHeader("CR-Gateway-Signatures");if(a){for(var b=0,c=[],a=a.split(";");b<a.length;b++)""!=a[b]&&c.push(a[b].split(":"));e(s.response,d,c)}}else{if(401==s.status)throw Error("CloudrailClient Error: Invalid ClientID");d&&d(null)}};s.send()};a.initService=function(b){return a.getService(b)};a.j=function(a,c,d){if("object"!==typeof a||!(a instanceof b))throw Error("1. parameter typ fail");
if("object"!==typeof c)throw Error("2. parameter typ fail");if("function"!==typeof d)throw Error("3. (callback) parameter is no function");};a.create=function(b,c,d){this.j(b,c,d);c instanceof Array||(c=[c]);a.getService(b._identifier_service_tag,function(a,b,c){return function(d){var e=a._object_type,g=a._identifier_service_tag;if(!d)throw Error("No Services found!");var g=g.toLowerCase(),h=void 0;"object"==typeof d&&d instanceof t&&(h=d.h);if(void 0==h)throw Error("No Services found!");if(void 0==
h[e])throw Error("Service no Supported!");d=h[e];h=0;try{h=JSON.stringify(a).length}catch(n){}if(void 0==d.d[k])throw Error("Methode no Supported!");f.updateRequest(g,e,k,h);d.d[k](a,b,function(a,b,c){return function(d){var e=d.getStatus(),g=0,h=0;200<=e&&300>e||(400<=e&&500>e?h=1:500<=e&&(g=1));f.updateResponse(a,b,k,0,g,h);c(d)}}(g,e,c))}}(b,c,d))};a.read=function(b,c,d){this.j(b,c,d);c instanceof Array||(c=[c]);a.getService(b._identifier_service_tag,function(a,b,c){return function(d){var e=a._object_type,
g=a._identifier_service_tag;if(!d)throw Error("No Services found!");var g=g.toLowerCase(),h=void 0;"object"==typeof d&&d instanceof t&&(h=d.h);if(void 0==h)throw Error("No Services found!");if(void 0==h[e])throw Error("Service no Supported!");d=h[e];h=0;try{h=JSON.stringify(a).length}catch(k){}if(void 0==d.d[m])throw Error("Methode no Supported!");f.updateRequest(g,e,m,h);d.d[m](a,b,function(a,b,c){return function(d){var e=d.getStatus(),g=0,h=0,k=0;200<=e&&300>e?g=d.getResultsByteLength():400<=e&&
500>e?k=1:500<=e&&(h=1);f.updateResponse(a,b,m,g,h,k);c(d)}}(g,e,c))}}(b,c,d))};a.update=function(b,c,d){this.j(b,c,d);c instanceof Array||(c=[c]);a.getService(b._identifier_service_tag,function(a,b,c){return function(d){var e=a._object_type,g=a._identifier_service_tag;if(!d)throw Error("No Services found!");var g=g.toLowerCase(),h=void 0;"object"==typeof d&&d instanceof t&&(h=d.h);if(void 0==h)throw Error("No Services found!");if(void 0==h[e])throw Error("Service no Supported!");d=h[e];h=0;try{h=
JSON.stringify(a).length}catch(k){}if(void 0==d.d[q])throw Error("Methode no Supported!");f.updateRequest(g,e,q,h);d.d[q](a,b,function(a,b,c){return function(d){var e=d.getStatus(),g=0,h=0;200<=e&&300>e||(400<=e&&500>e?h=1:500<=e&&(g=1));f.updateResponse(a,b,q,0,g,h);c(d)}}(g,e,c))}}(b,c,d))};a.remove=function(b,c,d){this.j(b,c,d);c instanceof Array||(c=[c]);a.getService(b._identifier_service_tag,function(a,b,c){return function(d){var e=a._object_type,g=a._identifier_service_tag;if(!d)throw Error("No Services found!");
var g=g.toLowerCase(),h=void 0;"object"==typeof d&&d instanceof t&&(h=d.h);if(void 0==h)throw Error("No Services found!");if(void 0==h[e])throw Error("Service no Supported!");d=h[e];h=0;try{h=JSON.stringify(a).length}catch(k){}if(void 0==d.d[r])throw Error("Methode no Supported!");f.updateRequest(g,e,r,h);d.d[r](a,b,function(a,b,c){return function(d){var e=d.getStatus(),g=0,h=0;200<=e&&300>e||(400<=e&&500>e?h=1:500<=e&&(g=1));f.updateResponse(a,b,r,0,g,h);c(d)}}(g,e,c))}}(b,c,d))};e.hasOwnProperty("CloudRailClient")||
(e.CloudRailClient=c)})(window);
(function(e){function c(){}var a=e.CloudRailClient||{},b=a.Crypto=a.Crypto||{},b=b.Random=b.Random||{};a.VERSION="1.0.0";a.PLATFORM="JavaScript/HTML5";e.Blob.hasOwnProperty("slice")||(e.Blob.hasOwnProperty("webkitSlice")?e.Blob.prototype.slice=e.Blob.prototype.webkitSlice:e.Blob.hasOwnProperty("mozSlice")&&(e.Blob.prototype.slice=e.Blob.prototype.mozSlice));a.AccessAuthorization=function(){};a.AccessAuthorization.prototype=new a.Node;a.K=b.getArrayBuffer(16);a.G=a.Converter.ArrayBuffer.toBase64Url(a.K);a.t=
"";a.setClientID=function(b){if(null===/^[A-Za-z0-9\-\_]{22}$/.exec(b))throw Error("Bad client ID format");a.t=b};a.Config=a.Config||{};a.Config.LocalUriCallback={};a.Config.LocalUriCallback.setBaseUri=function(a){this.m=a};a.Config.LocalUriCallback.getBaseUri=function(){if(void 0==this.m){var a;if(e.URL)try{(a=new e.URL(document.URL))&&a.protocol&&a.host&&a.pathname&&a.search||(a=e.location)}catch(b){a=e.location}else a=e.location;this.m=a.protocol+"//"+a.host+a.pathname+a.search}return this.m};
c.IO=a.IO=a.IO||{};c.Uri=a.Uri=a.Uri;a.Math=a.Math||{};a.LocalEvent=a.LocalEvent;a.Storage=a.Storage||{};a.Storage.SandboxCache=a.Storage.SandboxCache;c.prototype={CloudRailInterface:a.CloudRailInterface,IO:c.IO,Uri:c.Uri,Math:a.Math,Date:a.Date,Timer:a.Timer,LocalEvent:a.LocalEvent,SandboxCache:a.Storage.SandboxCache,NodeIdentifier:a.NodeIdentifier,Node:a.Node,Identity:a.Identity,ClientIdentity:a.ClientIdentity,UserIdentity:a.UserIdentity,UserAccountInfo:a.UserAccountInfo,FileStorage:a.FileStorage,
File:a.File,Thumbnail:a.Thumbnail};a.Sandbox=c;e.hasOwnProperty("CloudRailClient")||(e.CloudRailClient=a)})(window);





/*
 

 Javascript SHA-256 implementation.

 An older version of this implementation is available in the public
 domain, but this one is (c) Emily Stark, Mike Hamburg, Dan Boneh,
 Stanford University 2008-2010 and BSD-licensed for liability
 reasons.

 Special thanks to Aldo Cortesi for pointing out several bugs in
 this code.

 @author Emily Stark
 @author Mike Hamburg
 @author Dan Boneh
*/
(function(q){var h=q.CloudRailClient||{},l=h.Crypto=h.Crypto||{},l=l.Hash=l.Hash||{},m=h.Converter=h.Converter||{},d=m.ArrayBuffer=m.ArrayBuffer||{},r=d.change32BitByteEndian,s=(m.String=m.String||{}).toArrayBuffer,t=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],u=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,
264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298],e=l.SHA256=
function(a){a?(this.c=new BufferArray(a.c),this.a=new BufferArray(a.a),this.b=a.b):this.reset()};e.hash=function(a){return(new e).update(a).finalize()};e.prototype.reset=function(){this.c=(new Uint32Array(t)).buffer;this.a=new ArrayBuffer;this.b=0;return this};e.prototype.update=function(a){"string"===typeof a&&(a=s(a));this.a=d.concat(this.a,a);var c,f=this.a;c=this.b;a=this.b=c+a.byteLength;var b=0;for(c=64+c&-64;c<=a;c+=64)this.d(d.slice(f,64*b,64*(b+1))),++b;this.a=d.slice(f,64*b,f.byteLength);
return this};e.prototype.finalize=function(){var a=this.a,c=[],f=8*this.b,b=new ArrayBuffer(64-(a.byteLength+9)%64),e=new Uint8Array(1);e[0]=128;a=d.concat(a,e.buffer);a=d.concat(a,b);c.push(Math.floor(f/4294967296));c.push(f|0);a=d.concat(a,r((new Uint32Array(c)).buffer));for(c=0;a.byteLength>64*c;)this.d(d.slice(a,64*c,64*(c+1))),++c;a=new ArrayBuffer(32);(new Uint8Array(a)).set(new Uint8Array(this.c));this.reset();return a=r(a)};e.prototype.d=function(a){var c,f,b=new Uint32Array(this.c,0,8),e=
b[0],g=b[1],d=b[2],h=b[3],k=b[4],l=b[5],p=b[6],m=b[7],n=new Uint32Array(80);a=new Uint32Array(r(a));n.set(a,0);for(a=0;64>a;++a)16>a?c=n[a]:(c=n[a+1&15],f=n[a+14&15],c=n[a&15]=(c>>>7^c>>>18^c>>>3^c<<25^c<<14)+(f>>>17^f>>>19^f>>>10^f<<15^f<<13)+n[a&15]+n[a+9&15]|0),c=c+m+(k>>>6^k>>>11^k>>>25^k<<26^k<<21^k<<7)+(p^k&(l^p))+u[a],m=p,p=l,l=k,k=h+c|0,h=d,d=g,g=e,e=c+(g&d^h&(g^d))+(g>>>2^g>>>13^g>>>22^g<<30^g<<19^g<<10)|0;b[0]=b[0]+e|0;b[1]=b[1]+g|0;b[2]=b[2]+d|0;b[3]=b[3]+h|0;b[4]=b[4]+k|0;b[5]=b[5]+l|
0;b[6]=b[6]+p|0;b[7]=b[7]+m|0};q.hasOwnProperty("CloudRailClient")||(q.CloudRailClient=h)})(window);





/*
 (c) 2003-2005  Tom Wu
 @license 
 Permission is hereby granted, free of charge, to any person obtaining
 a copy of this software and associated documentation files (the
 "Software"), to deal in the Software without restriction, including
 without limitation the rights to use, copy, modify, merge, publish,
 distribute, sublicense, and/or sell copies of the Software, and to
 permit persons to whom the Software is furnished to do so, subject to
 the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS-IS" AND WITHOUT WARRANTY OF ANY KIND, 
 EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY 
 WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  

 IN NO EVENT SHALL TOM WU BE LIABLE FOR ANY SPECIAL, INCIDENTAL,
 INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER
 RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT ADVISED OF
 THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF LIABILITY, ARISING OUT
 OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

 In addition, the following condition applies:

 All redistributions must retain an intact copy of this copyright notice
 and disclaimer.

 @author Tom Wu
*/
var Q={};
(function(Z){function D(){this.ab=2048;this.bb="010001";this.log=!1;this.key=null}function F(a){v.call(this);a&&("string"===typeof a?this.gc(a):(this.Lb(a)||this.Mb(a))&&this.ic(a))}function e(a,c,b){null!=a&&("number"==typeof a?this.xa(a,c,b):null==c&&"string"!=typeof a?this.ya(a,256):this.ya(a,c))}function n(){return new e(null)}function $(a,c,b,d,f,h){for(;0<=--h;){var k=c*this[a++]+b[d]+f;f=Math.floor(k/67108864);b[d++]=k&67108863}return f}function aa(a,c,b,d,f,h){var k=c&32767;for(c>>=15;0<=
--h;){var g=this[a]&32767,e=this[a++]>>15,l=c*g+e*k,g=k*g+((l&32767)<<15)+b[d]+(f&1073741823);f=(g>>>30)+(l>>>15)+c*e+(f>>>30);b[d++]=g&1073741823}return f}function ba(a,c,b,d,f,h){var e=c&16383;for(c>>=14;0<=--h;){var g=this[a]&16383,l=this[a++]>>14,n=c*g+l*e,g=e*g+((n&16383)<<14)+b[d]+f;f=(g>>28)+(n>>14)+c*l;b[d++]=g&268435455}return f}function T(a){return"0123456789abcdefghijklmnopqrstuvwxyz".charAt(a)}function U(a,c){var b=I[a.charCodeAt(c)];return null==b?-1:b}function z(a){var c=n();c.Q(a);
return c}function J(a){var c=1,b;0!=(b=a>>>16)&&(a=b,c+=16);0!=(b=a>>8)&&(a=b,c+=8);0!=(b=a>>4)&&(a=b,c+=4);0!=(b=a>>2)&&(a=b,c+=2);0!=a>>1&&(c+=1);return c}function B(a){this.h=a}function C(a){this.h=a;this.ob=a.Pb();this.pb=this.ob&32767;this.Yb=this.ob>>15;this.Cc=(1<<a.d-15)-1;this.Zb=2*a.a}function V(a,c){return a|c}function ca(a,c){return a^c}function G(){}function W(a){return a}function E(a){this.O=n();this.rb=n();e.ONE.Z(2*a.a,this.O);this.$b=this.O.Eb(a);this.h=a}function M(){this.da=this.N=
0;this.t=[]}function N(){}function w(a){return new e(a,16)}function v(){this.B=null;this.L=0;this.X=this.aa=this.$=this.j=this.i=this.G=null}function q(a,c){a instanceof q?(this.ba=a.ba,this.o=a.o):(this.ba=a,this.o=c)}function p(a,c,b,d,f){this.stream=a;this.pa=c;this.length=b;this.tag=d;this.sub=f}var m;"Microsoft Internet Explorer"==navigator.appName?(e.prototype.w=aa,m=30):"Netscape"!=navigator.appName?(e.prototype.w=$,m=26):(e.prototype.w=ba,m=28);e.prototype.d=m;e.prototype.q=(1<<m)-1;e.prototype.s=
1<<m;e.prototype.yb=Math.pow(2,52);e.prototype.Wa=52-m;e.prototype.Xa=2*m-52;var I=[],r;m=48;for(r=0;9>=r;++r)I[m++]=r;m=97;for(r=10;36>r;++r)I[m++]=r;m=65;for(r=10;36>r;++r)I[m++]=r;B.prototype.Y=function(a){return 0>a.c||0<=a.f(this.h)?a.T(this.h):a};B.prototype.ga=function(a){return a};B.prototype.reduce=function(a){a.P(this.h,null,a)};B.prototype.U=function(a,c,b){a.fa(c,b);this.reduce(b)};B.prototype.K=function(a,c){a.ta(c);this.reduce(c)};C.prototype.Y=function(a){var c=n();a.abs().Z(this.h.a,
c);c.P(this.h,null,c);0>a.c&&0<c.f(e.ZERO)&&this.h.e(c,c);return c};C.prototype.ga=function(a){var c=n();a.copyTo(c);this.reduce(c);return c};C.prototype.reduce=function(a){for(;a.a<=this.Zb;)a[a.a++]=0;for(var c=0;c<this.h.a;++c){var b=a[c]&32767,d=b*this.pb+((b*this.Yb+(a[c]>>15)*this.pb&this.Cc)<<15)&a.q,b=c+this.h.a;for(a[b]+=this.h.w(0,d,a,c,0,this.h.a);a[b]>=a.s;)a[b]-=a.s,a[++b]++}a.r();a.la(this.h.a,a);0<=a.f(this.h)&&a.e(this.h,a)};C.prototype.U=function(a,c,b){a.fa(c,b);this.reduce(b)};
C.prototype.K=function(a,c){a.ta(c);this.reduce(c)};e.prototype.copyTo=function(a){for(var c=this.a-1;0<=c;--c)a[c]=this[c];a.a=this.a;a.c=this.c};e.prototype.Q=function(a){this.a=1;this.c=0>a?-1:0;0<a?this[0]=a:-1>a?this[0]=a+DV:this.a=0};e.prototype.ya=function(a,c){var b;if(16==c)b=4;else if(8==c)b=3;else if(256==c)b=8;else if(2==c)b=1;else if(32==c)b=5;else if(4==c)b=2;else{this.Fb(a,c);return}this.c=this.a=0;for(var d=a.length,f=!1,h=0;0<=--d;){var k=8==b?a[d]&255:U(a,d);0>k?"-"==a.charAt(d)&&
(f=!0):(f=!1,0==h?this[this.a++]=k:h+b>this.d?(this[this.a-1]|=(k&(1<<this.d-h)-1)<<h,this[this.a++]=k>>this.d-h):this[this.a-1]|=k<<h,h+=b,h>=this.d&&(h-=this.d))}8==b&&0!=(a[0]&128)&&(this.c=-1,0<h&&(this[this.a-1]|=(1<<this.d-h)-1<<h));this.r();f&&e.ZERO.e(this,this)};e.prototype.r=function(){for(var a=this.c&this.q;0<this.a&&this[this.a-1]==a;)--this.a};e.prototype.Z=function(a,c){var b;for(b=this.a-1;0<=b;--b)c[b+a]=this[b];for(b=a-1;0<=b;--b)c[b]=0;c.a=this.a+a;c.c=this.c};e.prototype.la=function(a,
c){for(var b=a;b<this.a;++b)c[b-a]=this[b];c.a=Math.max(this.a-a,0);c.c=this.c};e.prototype.S=function(a,c){var b=a%this.d,d=this.d-b,f=(1<<d)-1,h=Math.floor(a/this.d),e=this.c<<b&this.q,g;for(g=this.a-1;0<=g;--g)c[g+h+1]=this[g]>>d|e,e=(this[g]&f)<<b;for(g=h-1;0<=g;--g)c[g]=0;c[h]=e;c.a=this.a+h+1;c.c=this.c;c.r()};e.prototype.k=function(a,c){c.c=this.c;var b=Math.floor(a/this.d);if(b>=this.a)c.a=0;else{var d=a%this.d,f=this.d-d,h=(1<<d)-1;c[0]=this[b]>>d;for(var e=b+1;e<this.a;++e)c[e-b-1]|=(this[e]&
h)<<f,c[e-b]=this[e]>>d;0<d&&(c[this.a-b-1]|=(this.c&h)<<f);c.a=this.a-b;c.r()}};e.prototype.e=function(a,c){for(var b=0,d=0,f=Math.min(a.a,this.a);b<f;)d+=this[b]-a[b],c[b++]=d&this.q,d>>=this.d;if(a.a<this.a){for(d-=a.c;b<this.a;)d+=this[b],c[b++]=d&this.q,d>>=this.d;d+=this.c}else{for(d+=this.c;b<a.a;)d-=a[b],c[b++]=d&this.q,d>>=this.d;d-=a.c}c.c=0>d?-1:0;-1>d?c[b++]=this.s+d:0<d&&(c[b++]=d);c.a=b;c.r()};e.prototype.fa=function(a,c){var b=this.abs(),d=a.abs(),f=b.a;for(c.a=f+d.a;0<=--f;)c[f]=0;
for(f=0;f<d.a;++f)c[f+b.a]=b.w(0,d[f],c,f,0,b.a);c.c=0;c.r();this.c!=a.c&&e.ZERO.e(c,c)};e.prototype.ta=function(a){for(var c=this.abs(),b=a.a=2*c.a;0<=--b;)a[b]=0;for(b=0;b<c.a-1;++b){var d=c.w(b,c[b],a,2*b,0,1);(a[b+c.a]+=c.w(b+1,2*c[b],a,2*b+1,d,c.a-b-1))>=c.s&&(a[b+c.a]-=c.s,a[b+c.a+1]=1)}0<a.a&&(a[a.a-1]+=c.w(b,c[b],a,2*b,0,1));a.c=0;a.r()};e.prototype.P=function(a,c,b){var d=a.abs();if(!(0>=d.a)){var f=this.abs();if(f.a<d.a)null!=c&&c.Q(0),null!=b&&this.copyTo(b);else{null==b&&(b=n());var h=
n(),k=this.c;a=a.c;var g=this.d-J(d[d.a-1]);0<g?(d.S(g,h),f.S(g,b)):(d.copyTo(h),f.copyTo(b));d=h.a;f=h[d-1];if(0!=f){var l=f*(1<<this.Wa)+(1<d?h[d-2]>>this.Xa:0),p=this.yb/l,l=(1<<this.Wa)/l,q=1<<this.Xa,t=b.a,m=t-d,s=null==c?n():c;h.Z(m,s);0<=b.f(s)&&(b[b.a++]=1,b.e(s,b));e.ONE.Z(d,s);for(s.e(h,h);h.a<d;)h[h.a++]=0;for(;0<=--m;){var r=b[--t]==f?this.q:Math.floor(b[t]*p+(b[t-1]+q)*l);if((b[t]+=h.w(0,r,b,m,0,d))<r)for(h.Z(m,s),b.e(s,b);b[t]<--r;)b.e(s,b)}null!=c&&(b.la(d,c),k!=a&&e.ZERO.e(c,c));b.a=
d;b.r();0<g&&b.k(g,b);0>k&&e.ZERO.e(b,b)}}}};e.prototype.Pb=function(){if(1>this.a)return 0;var a=this[0];if(0==(a&1))return 0;var c=a&3,c=c*(2-(a&15)*c)&15,c=c*(2-(a&255)*c)&255,c=c*(2-((a&65535)*c&65535))&65535,c=c*(2-a*c%this.s)%this.s;return 0<c?this.s-c:-c};e.prototype.p=function(){return 0==(0<this.a?this[0]&1:this.c)};e.prototype.exp=function(a,c){if(4294967295<a||1>a)return e.ONE;var b=n(),d=n(),f=c.Y(this),h=J(a)-1;for(f.copyTo(b);0<=--h;)if(c.K(b,d),0<(a&1<<h))c.U(d,f,b);else var k=b,b=
d,d=k;return c.ga(b)};e.prototype.toString=function(a){if(0>this.c)return"-"+this.V().toString(a);if(16==a)a=4;else if(8==a)a=3;else if(2==a)a=1;else if(32==a)a=5;else if(4==a)a=2;else return this.Ac(a);var c=(1<<a)-1,b,d=!1,f="",h=this.a,e=this.d-h*this.d%a;if(0<h--)for(e<this.d&&0<(b=this[h]>>e)&&(d=!0,f=T(b));0<=h;)e<a?(b=(this[h]&(1<<e)-1)<<a-e,b|=this[--h]>>(e+=this.d-a)):(b=this[h]>>(e-=a)&c,0>=e&&(e+=this.d,--h)),0<b&&(d=!0),d&&(f+=T(b));return d?f:"0"};e.prototype.V=function(){var a=n();e.ZERO.e(this,
a);return a};e.prototype.abs=function(){return 0>this.c?this.V():this};e.prototype.f=function(a){var c=this.c-a.c;if(0!=c)return c;var b=this.a,c=b-a.a;if(0!=c)return 0>this.c?-c:c;for(;0<=--b;)if(0!=(c=this[b]-a[b]))return c;return 0};e.prototype.ka=function(){return 0>=this.a?0:this.d*(this.a-1)+J(this[this.a-1]^this.c&this.q)};e.prototype.T=function(a){var c=n();this.abs().P(a,null,c);0>this.c&&0<c.f(e.ZERO)&&a.e(c,c);return c};e.prototype.nb=function(a,c){var b;b=256>a||c.p()?new B(c):new C(c);
return this.exp(a,b)};e.ZERO=z(0);e.ONE=z(1);G.prototype.Y=W;G.prototype.ga=W;G.prototype.U=function(a,c,b){a.fa(c,b)};G.prototype.K=function(a,c){a.ta(c)};E.prototype.Y=function(a){if(0>a.c||a.a>2*this.h.a)return a.T(this.h);if(0>a.f(this.h))return a;var c=n();a.copyTo(c);this.reduce(c);return c};E.prototype.ga=function(a){return a};E.prototype.reduce=function(a){a.la(this.h.a-1,this.O);a.a>this.h.a+1&&(a.a=this.h.a+1,a.r());this.$b.bc(this.O,this.h.a+1,this.rb);for(this.h.ac(this.rb,this.h.a+1,
this.O);0>a.f(this.O);)a.M(1,this.h.a+1);for(a.e(this.O,a);0<=a.f(this.h);)a.e(this.h,a)};E.prototype.U=function(a,c,b){a.fa(c,b);this.reduce(b)};E.prototype.K=function(a,c){a.ta(c);this.reduce(c)};var u=[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,
431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997],da=67108864/u[u.length-1];e.prototype.Ya=function(a){return Math.floor(Math.LN2*this.d/Math.log(a))};e.prototype.Ac=function(a){null==a&&(a=10);if(0==this.J()||
2>a||36<a)return"0";var c=this.Ya(a),c=Math.pow(a,c),b=z(c),d=n(),f=n(),h="";for(this.P(b,d,f);0<d.J();)h=(c+f.lb()).toString(a).substr(1)+h,d.P(b,d,f);return f.lb().toString(a)+h};e.prototype.Fb=function(a,c){this.Q(0);null==c&&(c=10);for(var b=this.Ya(c),d=Math.pow(c,b),f=!1,h=0,k=0,g=0;g<a.length;++g){var l=U(a,g);0>l?"-"==a.charAt(g)&&0==this.J()&&(f=!0):(k=c*k+l,++h>=b&&(this.Za(d),this.M(k,0),k=h=0))}0<h&&(this.Za(Math.pow(c,h)),this.M(k,0));f&&e.ZERO.e(this,this)};e.prototype.xa=function(a,
c,b){if("number"==typeof c)if(2>a)this.Q(1);else for(this.xa(a,b),this.vb(a-1)||this.va(e.ONE.shiftLeft(a-1),V,this),this.p()&&this.M(1,0);!this.R(c);)this.M(2,0),this.ka()>a&&this.e(e.ONE.shiftLeft(a-1),this);else{b=[];var d=a&7;b.length=(a>>3)+1;c.dc(b);b[0]=0<d?b[0]&(1<<d)-1:0;this.ya(b,256)}};e.prototype.va=function(a,c,b){var d,f,h=Math.min(a.a,this.a);for(d=0;d<h;++d)b[d]=c(this[d],a[d]);if(a.a<this.a){f=a.c&this.q;for(d=h;d<this.a;++d)b[d]=c(this[d],f);b.a=this.a}else{f=this.c&this.q;for(d=
h;d<a.a;++d)b[d]=c(f,a[d]);b.a=a.a}b.c=c(this.c,a.c);b.r()};e.prototype.ia=function(a,c){for(var b=0,d=0,f=Math.min(a.a,this.a);b<f;)d+=this[b]+a[b],c[b++]=d&this.q,d>>=this.d;if(a.a<this.a){for(d+=a.c;b<this.a;)d+=this[b],c[b++]=d&this.q,d>>=this.d;d+=this.c}else{for(d+=this.c;b<a.a;)d+=a[b],c[b++]=d&this.q,d>>=this.d;d+=a.c}c.c=0>d?-1:0;0<d?c[b++]=d:-1>d&&(c[b++]=this.s+d);c.a=b;c.r()};e.prototype.Za=function(a){this[this.a]=this.w(0,a-1,this,0,0,this.a);++this.a;this.r()};e.prototype.M=function(a,
c){if(0!=a){for(;this.a<=c;)this[this.a++]=0;for(this[c]+=a;this[c]>=this.s;)this[c]-=this.s,++c>=this.a&&(this[this.a++]=0),++this[c]}};e.prototype.ac=function(a,c,b){var d=Math.min(this.a+a.a,c);b.c=0;for(b.a=d;0<d;)b[--d]=0;var f;for(f=b.a-this.a;d<f;++d)b[d+this.a]=this.w(0,a[d],b,d,0,this.a);for(f=Math.min(a.a,c);d<f;++d)this.w(0,a[d],b,d,0,c-d);b.r()};e.prototype.bc=function(a,c,b){--c;var d=b.a=this.a+a.a-c;for(b.c=0;0<=--d;)b[d]=0;for(d=Math.max(c-this.a,0);d<a.a;++d)b[this.a+d-c]=this.w(c-
d,a[d],b,0,0,this.a+d-c);b.r();b.la(1,b)};e.prototype.Wb=function(a){if(0>=a)return 0;var c=this.s%a,b=0>this.c?a-1:0;if(0<this.a)if(0==c)b=this[0]%a;else for(var d=this.a-1;0<=d;--d)b=(c*b+this[d])%a;return b};e.prototype.Vb=function(a){var c=this.C(e.ONE),b=c.I();if(0>=b)return!1;var d=c.yc(b);a=a+1>>1;a>u.length&&(a=u.length);for(var f=n(),h=0;h<a;++h){f.Q(u[Math.floor(Math.random()*u.length)]);var k=f.Xb(d,this);if(0!=k.f(e.ONE)&&0!=k.f(c)){for(var g=1;g++<b&&0!=k.f(c);)if(k=k.nb(2,this),0==k.f(e.ONE))return!1;
if(0!=k.f(c))return!1}}return!0};e.prototype.clone=function(){var a=n();this.copyTo(a);return a};e.prototype.lb=function(){if(0>this.c){if(1==this.a)return this[0]-this.s;if(0==this.a)return-1}else{if(1==this.a)return this[0];if(0==this.a)return 0}return(this[1]&(1<<32-this.d)-1)<<this.d|this[0]};e.prototype.J=function(){return 0>this.c?-1:0>=this.a||1==this.a&&0>=this[0]?0:1};e.prototype.zc=function(){var a=this.a,c=[];c[0]=this.c;var b=this.d-a*this.d%8,d,f=0;if(0<a--)for(b<this.d&&(d=this[a]>>
b)!=(this.c&this.q)>>b&&(c[f++]=d|this.c<<this.d-b);0<=a;)if(8>b?(d=(this[a]&(1<<b)-1)<<8-b,d|=this[--a]>>(b+=this.d-8)):(d=this[a]>>(b-=8)&255,0>=b&&(b+=this.d,--a)),0!=(d&128)&&(d|=-256),0==f&&(this.c&128)!=(d&128)&&++f,0<f||d!=this.c)c[f++]=d;return c};e.prototype.min=function(a){return 0>this.f(a)?this:a};e.prototype.max=function(a){return 0<this.f(a)?this:a};e.prototype.Fc=function(a){var c=n();this.va(a,ca,c);return c};e.prototype.shiftLeft=function(a){var c=n();0>a?this.k(-a,c):this.S(a,c);
return c};e.prototype.yc=function(a){var c=n();0>a?this.S(-a,c):this.k(a,c);return c};e.prototype.I=function(){for(var a=0;a<this.a;++a)if(0!=this[a]){var c;c=this[a];if(0==c)c=-1;else{var b=0;0==(c&65535)&&(c>>=16,b+=16);0==(c&255)&&(c>>=8,b+=8);0==(c&15)&&(c>>=4,b+=4);0==(c&3)&&(c>>=2,b+=2);0==(c&1)&&++b;c=b}return a*this.d+c}return 0>this.c?this.a*this.d:-1};e.prototype.vb=function(a){var c=Math.floor(a/this.d);return c>=this.a?0!=this.c:0!=(this[c]&1<<a%this.d)};e.prototype.add=function(a){var c=
n();this.ia(a,c);return c};e.prototype.C=function(a){var c=n();this.e(a,c);return c};e.prototype.multiply=function(a){var c=n();this.fa(a,c);return c};e.prototype.Eb=function(a){var c=n();this.P(a,c,null);return c};e.prototype.Xb=function(a,c){var b=a.ka(),d,f=z(1),h;if(0>=b)return f;d=18>b?1:48>b?3:144>b?4:768>b?5:6;h=8>b?new B(c):c.p()?new E(c):new C(c);var e=[],g=3,l=d-1,p=(1<<d)-1;e[1]=h.Y(this);if(1<d)for(b=n(),h.K(e[1],b);g<=p;)e[g]=n(),h.U(b,e[g-2],e[g]),g+=2;for(var m=a.a-1,t,q=!0,s=n(),b=
J(a[m])-1;0<=m;){b>=l?t=a[m]>>b-l&p:(t=(a[m]&(1<<b+1)-1)<<l-b,0<m&&(t|=a[m-1]>>this.d+b-l));for(g=d;0==(t&1);)t>>=1,--g;0>(b-=g)&&(b+=this.d,--m);if(q)e[t].copyTo(f),q=!1;else{for(;1<g;)h.K(f,s),h.K(s,f),g-=2;0<g?h.K(f,s):(g=f,f=s,s=g);h.U(s,e[t],f)}for(;0<=m&&0==(a[m]&1<<b);)h.K(f,s),g=f,f=s,s=g,0>--b&&(b=this.d-1,--m)}return h.ga(f)};e.prototype.ra=function(a){var c=a.p();if(this.p()&&c||0==a.J())return e.ZERO;for(var b=a.clone(),d=this.clone(),f=z(1),h=z(0),k=z(0),g=z(1);0!=b.J();){for(;b.p();)b.k(1,
b),c?(f.p()&&h.p()||(f.ia(this,f),h.e(a,h)),f.k(1,f)):h.p()||h.e(a,h),h.k(1,h);for(;d.p();)d.k(1,d),c?(k.p()&&g.p()||(k.ia(this,k),g.e(a,g)),k.k(1,k)):g.p()||g.e(a,g),g.k(1,g);0<=b.f(d)?(b.e(d,b),c&&f.e(k,f),h.e(g,h)):(d.e(b,d),c&&k.e(f,k),g.e(h,g))}if(0!=d.f(e.ONE))return e.ZERO;if(0<=g.f(a))return g.C(a);if(0>g.J())g.ia(a,g);else return g;return 0>g.J()?g.add(a):g};e.prototype.pow=function(a){return this.exp(a,new G)};e.prototype.na=function(a){var c=0>this.c?this.V():this.clone();a=0>a.c?a.V():
a.clone();if(0>c.f(a)){var b=c,c=a;a=b}var b=c.I(),d=a.I();if(0>d)return c;b<d&&(d=b);0<d&&(c.k(d,c),a.k(d,a));for(;0<c.J();)0<(b=c.I())&&c.k(b,c),0<(b=a.I())&&a.k(b,a),0<=c.f(a)?(c.e(a,c),c.k(1,c)):(a.e(c,a),a.k(1,a));0<d&&a.S(d,a);return a};e.prototype.R=function(a){var c,b=this.abs();if(1==b.a&&b[0]<=u[u.length-1]){for(c=0;c<u.length;++c)if(b[0]==u[c])return!0;return!1}if(b.p())return!1;for(c=1;c<u.length;){for(var d=u[c],f=c+1;f<u.length&&d<da;)d*=u[f++];for(d=b.Wb(d);c<f;)if(0==d%u[c++])return!1}return b.Vb(a)};
M.prototype.Ob=function(a){var c,b,d;for(c=0;256>c;++c)this.t[c]=c;for(c=b=0;256>c;++c)b=b+this.t[c]+a[c%a.length]&255,d=this.t[c],this.t[c]=this.t[b],this.t[b]=d;this.da=this.N=0};M.prototype.next=function(){var a;this.N=this.N+1&255;this.da=this.da+this.t[this.N]&255;a=this.t[this.N];this.t[this.N]=this.t[this.da];this.t[this.da]=a;return this.t[a+this.t[this.N]&255]};var K,A,x;if(null==A){A=[];x=0;if(window.crypto&&window.crypto.getRandomValues)for(r=new Uint32Array(256),window.crypto.getRandomValues(r),
m=0;m<r.length;++m)A[x++]=r[m]&255;var L=function(a){this.count=this.count||0;256<=this.count||256<=x?window.removeEventListener?window.removeEventListener("mousemove",L):window.detachEvent&&window.detachEvent("onmousemove",L):(this.count+=1,a=a.x+a.y,A[x++]=a&255)};window.addEventListener?window.addEventListener("mousemove",L):window.attachEvent&&window.attachEvent("onmousemove",L)}N.prototype.dc=function(a){var c;for(c=0;c<a.length;++c){var b=c,d;if(null==K){for(K=new M;256>x;)d=Math.floor(65536*
Math.random()),A[x++]=d&255;K.Ob(A);for(x=0;x<A.length;++x)A[x]=0;x=0}d=K.next();a[b]=d}};v.prototype.cb=function(a){return a.nb(this.L,this.B)};v.prototype.Gb=function(a,c){var b=new N,d=a>>1;this.L=parseInt(c,16);for(var f=new e(c,16);;){for(;this.i=new e(a-d,1,b),0!=this.i.C(e.ONE).na(f).f(e.ONE)||!this.i.R(10););for(;this.j=new e(d,1,b),0!=this.j.C(e.ONE).na(f).f(e.ONE)||!this.j.R(10););if(0>=this.i.f(this.j)){var h=this.i;this.i=this.j;this.j=h}var h=this.i.C(e.ONE),k=this.j.C(e.ONE),g=h.multiply(k);
if(0==g.na(f).f(e.ONE)){this.B=this.i.multiply(this.j);this.G=f.ra(g);this.$=this.G.T(h);this.aa=this.G.T(k);this.X=this.j.ra(this.i);break}}};v.prototype.Hb=function(a,c,b){function d(){function c(){g.i=n();g.i.fb(a-h,f,function(){g.i.C(e.ONE).gb(k,function(a){0==a.f(e.ONE)&&g.i.R(10)?setTimeout(l,0):setTimeout(c,0)})})}function l(){g.j=n();g.j.fb(h,f,function(){g.j.C(e.ONE).gb(k,function(a){0==a.f(e.ONE)&&g.j.R(10)?setTimeout(m,0):setTimeout(l,0)})})}function m(){if(0>=g.i.f(g.j)){var a=g.i;g.i=
g.j;g.j=a}var a=g.i.C(e.ONE),c=g.j.C(e.ONE),f=a.multiply(c);0==f.na(k).f(e.ONE)?(g.B=g.i.multiply(g.j),g.G=k.ra(f),g.$=g.G.T(a),g.aa=g.G.T(c),g.X=g.j.ra(g.i),setTimeout(function(){b()},0)):setTimeout(d,0)}setTimeout(c,0)}var f=new N,h=a>>1;this.L=parseInt(c,16);var k=new e(c,16),g=this;setTimeout(d,0)};e.prototype.gb=function(a,c){var b=0>this.c?this.V():this.clone(),d=0>a.c?a.V():a.clone();if(0>b.f(d))var f=b,b=d,d=f;var h=b.I(),e=d.I();if(0>e)c(b);else{h<e&&(e=h);0<e&&(b.k(e,b),d.k(e,d));var g=
function(){0<(h=b.I())&&b.k(h,b);0<(h=d.I())&&d.k(h,d);0<=b.f(d)?(b.e(d,b),b.k(1,b)):(d.e(b,d),d.k(1,d));0<b.J()?setTimeout(g,0):(0<e&&d.S(e,d),setTimeout(function(){c(d)},0))};setTimeout(g,10)}};e.prototype.fb=function(a,c,b){if(2>a)this.Q(1);else{this.xa(a,c);this.vb(a-1)||this.va(e.ONE.shiftLeft(a-1),V,this);this.p()&&this.M(1,0);var d=this,f=function(){d.M(2,0);d.ka()>a&&d.e(e.ONE.shiftLeft(a-1),d);d.R(1)?setTimeout(function(){b()},0):setTimeout(f,0)};setTimeout(f,0)}};var l=l||{};l.ca=l.ca||
{};var O=l,P=Object.prototype,X=["toString","valueOf"];l.ca.mc=function(){function a(a){var c=0;return parseFloat(a.replace(/\./g,function(){return 1==c++?"":"."}))}var c=navigator,c={kb:0,opera:0,hb:0,Fa:0,chrome:0,ea:null,Bb:0,Qb:0,Rb:0,Sb:0,mb:null,Cb:0,Dc:0,Hc:c&&c.Ic,sc:!1,za:null},b=navigator&&navigator.userAgent,d=window&&window.location,d=d&&d.href;c.sc=d&&0===d.toLowerCase().indexOf("https");if(b){/windows|win32/i.test(b)?c.za="windows":/macintosh/i.test(b)?c.za="macintosh":/rhino/i.test(b)&&
(c.za="rhino");/KHTML/.test(b)&&(c.Fa=1);if((d=b.match(/AppleWebKit\/([^\s]*)/))&&d[1]){c.Fa=a(d[1]);if(/ Mobile\//.test(b))c.ea="Apple",(d=b.match(/OS ([^\s]*)/))&&d[1]&&(d=a(d[1].replace("_","."))),c.mb=d,c.Qb=c.Sb=c.Rb=0,(d=b.match(/iPad|iPod|iPhone/))&&d[0]&&(c[d[0].toLowerCase()]=c.mb);else{if(d=b.match(/NokiaN[^\/]*|Android \d\.\d|webOS\/\d\.\d/))c.ea=d[0];/webOS/.test(b)&&(c.ea="WebOS",(d=b.match(/webOS\/([^\s]*);/))&&d[1]&&(c.Dc=a(d[1])));/ Android/.test(b)&&(c.ea="Android",(d=b.match(/Android ([^\s]*);/))&&
d[1]&&(c.Cb=a(d[1])))}if((d=b.match(/Chrome\/([^\s]*)/))&&d[1])c.chrome=a(d[1]);else if(d=b.match(/AdobeAIR\/([^\s]*)/))c.Bb=d[0]}if(!c.Fa)if((d=b.match(/Opera[\s\/]([^\s]*)/))&&d[1]){if(c.opera=a(d[1]),(d=b.match(/Version\/([^\s]*)/))&&d[1]&&(c.opera=a(d[1])),d=b.match(/Opera Mini[^;]*/))c.ea=d[0]}else if((d=b.match(/MSIE\s([^;]*)/))&&d[1])c.kb=a(d[1]);else if(d=b.match(/Gecko\/([^\s]*)/))c.hb=1,(d=b.match(/rv:([^\s\)]*)/))&&d[1]&&(c.hb=a(d[1]))}return c};l.ca.Bc=l.ca.mc();l.Tb=function(a){return"function"===
typeof a||"[object Function]"===P.toString.apply(a)};l.Ab=l.ca.Bc.kb?function(a,c){var b,d,f;for(b=0;b<X.length;b+=1)d=X[b],f=c[d],O.Tb(f)&&f!=P[d]&&(a[d]=f)}:function(){};l.extend=function(a,c,b){function d(){}if(!c||!a)throw Error("extend failed, please check that all dependencies are included.");var f;d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;a.m=c.prototype;c.prototype.constructor==P.constructor&&(c.prototype.constructor=c);if(b){for(f in b)O.hasOwnProperty(b,f)&&(a.prototype[f]=
b[f]);O.Ab(a.prototype,b)}};"undefined"!=typeof KJUR&&KJUR||(KJUR={});"undefined"!=typeof KJUR.b&&KJUR.b||(KJUR.b={});KJUR.b.xb=new function(){this.Db=function(a){var c=a.toString(16);if("-"!=c.substr(0,1))1==c.length%2?c="0"+c:c.match(/^[0-7]/)||(c="00"+c);else{var b=c.substr(1).length;1==b%2?b+=1:c.match(/^[0-7]/)||(b+=2);for(var c="",d=0;d<b;d++)c+="f";c=(new e(c,16)).Fc(a).add(e.ONE).toString(16).replace(/^-/,"")}return c}};KJUR.b.D=function(){this.Ib=function(){if("undefined"==typeof this.g||
null==this.g)throw"this.hV is null or undefined.";if(1==this.g.length%2)throw"value hex must be even length: n=0,v="+this.g;var a=this.g.length/2,c=a.toString(16);1==c.length%2&&(c="0"+c);if(128>a)return c;var b=c.length/2;if(15<b)throw"ASN.1 length too long to represent by 8x: n = "+a.toString(16);return(128+b).toString(16)+c};this.oa=function(){if(null==this.n||this.v)this.g=this.H(),this.Jb=this.Ib(),this.n=this.l+this.Jb+this.g,this.v=!1;return this.n};this.H=function(){return""}};KJUR.b.F=function(a){KJUR.b.F.m.constructor.call(this);
this.sa=function(a){this.n=null;this.v=!0;this.c=a;this.g=stohex(this.c)};this.Ca=function(a){this.n=null;this.v=!0;this.c=null;this.g=a};this.H=function(){return this.g};"undefined"!=typeof a&&("undefined"!=typeof a.str?this.sa(a.str):"undefined"!=typeof a.hex&&this.Ca(a.hex))};l.extend(KJUR.b.F,KJUR.b.D);KJUR.b.ha=function(){KJUR.b.ha.m.constructor.call(this);this.Ub=function(a){utc=a.getTime()+6E4*a.getTimezoneOffset();return new Date(utc)};this.eb=function(a,c){var b=this.Gc,d=this.Ub(a),f=String(d.getFullYear());
"utc"==c&&(f=f.substr(2,2));var e=b(String(d.getMonth()+1),2),k=b(String(d.getDate()),2),g=b(String(d.getHours()),2),l=b(String(d.getMinutes()),2),b=b(String(d.getSeconds()),2);return f+e+k+g+l+b+"Z"};this.Gc=function(a,c){return a.length>=c?a:Array(c-a.length+1).join("0")+a};this.sa=function(a){this.n=null;this.v=!0;this.c=a;this.g=stohex(this.c)};this.H=function(){return this.g}};l.extend(KJUR.b.ha,KJUR.b.D);KJUR.b.ua=function(a){KJUR.b.F.m.constructor.call(this);this.W=[];"undefined"!=typeof a&&
"undefined"!=typeof a.array&&(this.W=a.array)};l.extend(KJUR.b.ua,KJUR.b.D);KJUR.b.Ha=function(){KJUR.b.Ha.m.constructor.call(this);this.l="01";this.n="0101ff"};l.extend(KJUR.b.Ha,KJUR.b.D);KJUR.b.Ka=function(a){KJUR.b.Ka.m.constructor.call(this);this.l="02";this.sb=function(a){this.n=null;this.v=!0;this.g=KJUR.b.xb.Db(a)};this.vc=function(a){a=new e(String(a),10);this.sb(a)};this.Da=function(a){this.g=a};this.H=function(){return this.g};"undefined"!=typeof a&&("undefined"!=typeof a.bigint?this.sb(a.bigint):
"undefined"!=typeof a["int"]?this.vc(a["int"]):"undefined"!=typeof a.hex&&this.Da(a.hex))};l.extend(KJUR.b.Ka,KJUR.b.D);KJUR.b.Ga=function(a){KJUR.b.Ga.m.constructor.call(this);this.l="03";this.wc=function(a){this.n=null;this.v=!0;this.g=a};this.tb=function(a){a=a.replace(/0+$/,"");var b=8-a.length%8;8==b&&(b=0);for(var d=0;d<=b;d++)a+="0";for(var f="",d=0;d<a.length-1;d+=8){var e=parseInt(a.substr(d,8),2).toString(16);1==e.length&&(e="0"+e);f+=e}this.n=null;this.v=!0;this.g="0"+b+f};this.uc=function(a){for(var b=
"",d=0;d<a.length;d++)b=1==a[d]?b+"1":b+"0";this.tb(b)};this.H=function(){return this.g};"undefined"!=typeof a&&("undefined"!=typeof a.hex?this.wc(a.hex):"undefined"!=typeof a.bin?this.tb(a.bin):"undefined"!=typeof a.array&&this.uc(a.array))};l.extend(KJUR.b.Ga,KJUR.b.D);KJUR.b.Oa=function(a){KJUR.b.Oa.m.constructor.call(this,a);this.l="04"};l.extend(KJUR.b.Oa,KJUR.b.F);KJUR.b.La=function(){KJUR.b.La.m.constructor.call(this);this.l="05";this.n="0500"};l.extend(KJUR.b.La,KJUR.b.D);KJUR.b.Na=function(a){function c(a){a=
a.toString(16);1==a.length&&(a="0"+a);return a}KJUR.b.Na.m.constructor.call(this);this.l="06";this.Da=function(a){this.n=null;this.v=!0;this.c=null;this.g=a};this.ub=function(a){if(!a.match(/^[0-9.]+$/))throw"malformed oid string: "+a;var d;a=a.split(".");d=""+c(40*parseInt(a[0])+parseInt(a[1]));a.splice(0,2);for(var f=0;f<a.length;f++){var h="",k=(new e(a[f],10)).toString(2),g=7-k.length%7;7==g&&(g=0);for(var l="",m=0;m<g;m++)l+="0";k=l+k;for(m=0;m<k.length-1;m+=7)g=k.substr(m,7),m!=k.length-7&&
(g="1"+g),h+=c(parseInt(g,2));d+=h}this.n=null;this.v=!0;this.c=null;this.g=d};this.xc=function(a){if("undefined"!=typeof KJUR.b.Ec.zb.cc[a])this.ub(KJUR.b.Ec.zb.cc[a]);else throw"DERObjectIdentifier oidName undefined: "+a;};this.H=function(){return this.g};"undefined"!=typeof a&&("undefined"!=typeof a.oid?this.ub(a.oid):"undefined"!=typeof a.hex?this.Da(a.hex):"undefined"!=typeof a.name&&this.xc(a.name))};l.extend(KJUR.b.Na,KJUR.b.D);KJUR.b.Va=function(a){KJUR.b.Va.m.constructor.call(this,a);this.l=
"0c"};l.extend(KJUR.b.Va,KJUR.b.F);KJUR.b.Ma=function(a){KJUR.b.Ma.m.constructor.call(this,a);this.l="12"};l.extend(KJUR.b.Ma,KJUR.b.F);KJUR.b.Pa=function(a){KJUR.b.Pa.m.constructor.call(this,a);this.l="13"};l.extend(KJUR.b.Pa,KJUR.b.F);KJUR.b.Ta=function(a){KJUR.b.Ta.m.constructor.call(this,a);this.l="14"};l.extend(KJUR.b.Ta,KJUR.b.F);KJUR.b.Ja=function(a){KJUR.b.Ja.m.constructor.call(this,a);this.l="16"};l.extend(KJUR.b.Ja,KJUR.b.F);KJUR.b.Ua=function(a){KJUR.b.Ua.m.constructor.call(this,a);this.l=
"17";this.Ba=function(a){this.n=null;this.v=!0;this.wa=a;this.c=this.eb(this.wa,"utc");this.g=stohex(this.c)};"undefined"!=typeof a&&("undefined"!=typeof a.str?this.sa(a.str):"undefined"!=typeof a.hex?this.Ca(a.hex):"undefined"!=typeof a.date&&this.Ba(a.date))};l.extend(KJUR.b.Ua,KJUR.b.ha);KJUR.b.Ia=function(a){KJUR.b.Ia.m.constructor.call(this,a);this.l="18";this.Ba=function(a){this.n=null;this.v=!0;this.wa=a;this.c=this.eb(this.wa,"gen");this.g=stohex(this.c)};"undefined"!=typeof a&&("undefined"!=
typeof a.str?this.sa(a.str):"undefined"!=typeof a.hex?this.Ca(a.hex):"undefined"!=typeof a.date&&this.Ba(a.date))};l.extend(KJUR.b.Ia,KJUR.b.ha);KJUR.b.Qa=function(a){KJUR.b.Qa.m.constructor.call(this,a);this.l="30";this.H=function(){for(var a="",b=0;b<this.W.length;b++)a+=this.W[b].oa();return this.g=a}};l.extend(KJUR.b.Qa,KJUR.b.ua);KJUR.b.Ra=function(a){KJUR.b.Ra.m.constructor.call(this,a);this.l="31";this.H=function(){for(var a=[],b=0;b<this.W.length;b++)a.push(this.W[b].oa());a.sort();return this.g=
a.join("")}};l.extend(KJUR.b.Ra,KJUR.b.ua);KJUR.b.Sa=function(a){KJUR.b.Sa.m.constructor.call(this);this.l="a0";this.g="";this.qa=!0;this.ja=null;this.tc=function(a,b,d){this.l=b;this.qa=a;this.ja=d;this.qa?(this.g=this.ja.oa(),this.n=null,this.v=!0):(this.g=null,this.n=d.oa(),this.n=this.n.replace(/^../,b),this.v=!1)};this.H=function(){return this.g};"undefined"!=typeof a&&("undefined"!=typeof a.tag&&(this.l=a.tag),"undefined"!=typeof a.explicit&&(this.qa=a.explicit),"undefined"!=typeof a.obj&&(this.ja=
a.obj,this.tc(this.qa,this.l,this.ja)))};l.extend(KJUR.b.Sa,KJUR.b.D);var Y={},y;Y.A=function(a){var c;if(void 0===y){var b="0123456789ABCDEF";y=[];for(c=0;16>c;++c)y[b.charAt(c)]=c;b=b.toLowerCase();for(c=10;16>c;++c)y[b.charAt(c)]=c;for(c=0;8>c;++c)y[" \f\n\r\t\u00a0\u2028\u2029".charAt(c)]=-1}var b=[],d=0,f=0;for(c=0;c<a.length;++c){var e=a.charAt(c);if("="==e)break;e=y[e];if(-1!=e){if(void 0===e)throw"Illegal character at offset "+c;d|=e;2<=++f?(b[b.length]=d,f=d=0):d<<=4}}if(f)throw"Hex encoding incomplete: 4 bits missing";
return b};var H={A:function(a){var c;if(void 0===y){y=[];for(c=0;64>c;++c)y["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c)]=c;for(c=0;9>c;++c)y["= \f\n\r\t\u00a0\u2028\u2029".charAt(c)]=-1}var b=[],d=0,f=0;for(c=0;c<a.length;++c){var e=a.charAt(c);if("="==e)break;e=y[e];if(-1!=e){if(void 0===e)throw"Illegal character at offset "+c;d|=e;4<=++f?(b[b.length]=d>>16,b[b.length]=d>>8&255,b[b.length]=d&255,f=d=0):d<<=6}}switch(f){case 1:throw"Base64 encoding incomplete: at least 2 bits missing";
case 2:b[b.length]=d>>10;break;case 3:b[b.length]=d>>16,b[b.length]=d>>8&255}return b},pc:/-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----|begin-base64[^\n]+\n([A-Za-z0-9+\/=\s]+)====/,Ea:function(a){var c=H.pc.exec(a);if(c)if(c[1])a=c[1];else if(c[2])a=c[2];else throw"RegExp out of sync";return H.A(a)}};q.prototype.get=function(a){void 0===a&&(a=this.o++);if(a>=this.ba.length)throw"Requesting byte offset "+a+" on a stream of length "+this.ba.length;return this.ba[a]};q.prototype.jb=
"0123456789ABCDEF";q.prototype.ib=function(a){return this.jb.charAt(a>>4&15)+this.jb.charAt(a&15)};q.prototype.Nb=function(a,c){for(var b="",d=a;d<c;++d)b+=this.ib(this.get(d));return b};q.prototype.Aa=function(a,c){for(var b="",d=a;d<c;++d)b+=String.fromCharCode(this.get(d));return b};q.prototype.kc=function(a,c){for(var b="",d=a;d<c;)var f=this.get(d++),b=128>f?b+String.fromCharCode(f):191<f&&224>f?b+String.fromCharCode((f&31)<<6|this.get(d++)&63):b+String.fromCharCode((f&15)<<12|(this.get(d++)&
63)<<6|this.get(d++)&63);return b};q.prototype.jc=function(a,c){for(var b="",d=a;d<c;d+=2)var f=this.get(d),e=this.get(d+1),b=b+String.fromCharCode((f<<8)+e);return b};q.prototype.rc=/^((?:1[89]|2\d)?\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/;q.prototype.lc=function(a,c){var b=this.Aa(a,c),d=this.rc.exec(b);if(!d)return"Unrecognized time: "+b;b=d[1]+"-"+d[2]+"-"+d[3]+" "+d[4];d[5]&&(b+=":"+d[5],d[6]&&
(b+=":"+d[6],d[7]&&(b+="."+d[7])));d[8]&&(b+=" UTC","Z"!=d[8]&&(b+=d[8],d[9]&&(b+=":"+d[9])));return b};q.prototype.fc=function(a,c){var b=c-a;if(4<b){var b=b<<3,d=this.get(a);if(0===d)b-=8;else for(;128>d;)d<<=1,--b;return"("+b+" bit)"}b=0;for(d=a;d<c;++d)b=b<<8|this.get(d);return b};q.prototype.ec=function(a,c){var b=this.get(a),d=(c-a-1<<3)-b,f="("+d+" bit)";if(20>=d)for(var e=b,f=f+" ",b=c-1;b>a;--b){for(d=this.get(b);8>e;++e)f+=d>>e&1?"1":"0";e=0}return f};q.prototype.qb=function(a,c){var b=
c-a,d="("+b+" byte) ";100<b&&(c=a+100);for(var f=a;f<c;++f)d+=this.ib(this.get(f));100<b&&(d+="\u2026");return d};q.prototype.hc=function(a,c){for(var b="",d=0,f=0,e=a;e<c;++e){var k=this.get(e),d=d<<7|k&127,f=f+7;k&128||(""===b?(b=80>d?40>d?0:1:2,b=b+"."+(d-40*b)):b+="."+(31<=f?"bigint":d),d=f=0)}return b};p.prototype.typeName=function(){if(void 0===this.tag)return"unknown";var a=this.tag&31;switch(this.tag>>6){case 0:switch(a){case 0:return"EOC";case 1:return"BOOLEAN";case 2:return"INTEGER";case 3:return"BIT_STRING";
case 4:return"OCTET_STRING";case 5:return"NULL";case 6:return"OBJECT_IDENTIFIER";case 7:return"ObjectDescriptor";case 8:return"EXTERNAL";case 9:return"REAL";case 10:return"ENUMERATED";case 11:return"EMBEDDED_PDV";case 12:return"UTF8String";case 16:return"SEQUENCE";case 17:return"SET";case 18:return"NumericString";case 19:return"PrintableString";case 20:return"TeletexString";case 21:return"VideotexString";case 22:return"IA5String";case 23:return"UTCTime";case 24:return"GeneralizedTime";case 25:return"GraphicString";
case 26:return"VisibleString";case 27:return"GeneralString";case 28:return"UniversalString";case 30:return"BMPString";default:return"Universal_"+a.toString(16)}case 1:return"Application_"+a.toString(16);case 2:return"["+a+"]";case 3:return"Private_"+a.toString(16)}};p.prototype.qc=/^[ -~]+$/;p.prototype.content=function(){if(void 0===this.tag)return null;var a=this.tag>>6,c=this.tag&31,b=this.nc(),d=Math.abs(this.length);if(0!==a){if(null!==this.sub)return"("+this.sub.length+" elem)";a=this.stream.Aa(b,
b+Math.min(d,100));return this.qc.test(a)?a.substring(0,200)+(200<a.length?"\u2026":""):this.stream.qb(b,b+d)}switch(c){case 1:return 0===this.stream.get(b)?"false":"true";case 2:return this.stream.fc(b,b+d);case 3:return this.sub?"("+this.sub.length+" elem)":this.stream.ec(b,b+d);case 4:return this.sub?"("+this.sub.length+" elem)":this.stream.qb(b,b+d);case 6:return this.stream.hc(b,b+d);case 16:case 17:return"("+this.sub.length+" elem)";case 12:return this.stream.kc(b,b+d);case 18:case 19:case 20:case 21:case 22:case 26:return this.stream.Aa(b,
b+d);case 30:return this.stream.jc(b,b+d);case 23:case 24:return this.stream.lc(b,b+d)}return null};p.prototype.toString=function(){return this.typeName()+"@"+this.stream.o+"[header:"+this.pa+",length:"+this.length+",sub:"+(null===this.sub?"null":this.sub.length)+"]"};p.prototype.nc=function(){return this.stream.o+this.pa};p.prototype.oc=function(){return this.stream.o+this.pa+Math.abs(this.length)};p.prototype.wb=function(){return this.stream.Nb(this.stream.o,this.oc())};p.$a=function(a){var c=a.get(),
b=c&127;if(b==c)return b;if(3<b)throw"Length over 24 bits not supported at position "+(a.o-1);if(0===b)return-1;for(var d=c=0;d<b;++d)c=c<<8|a.get();return c};p.Kb=function(a){return a&32?!0:!1};p.A=function(a,c){a instanceof q||(a=new q(a,0));var b=new q(a),d=a.get(),f=p.$a(a),e=a.o-b.o,k=null;if(p.Kb(d)||c){var g=a.o;3==d&&a.get();k=[];if(0<=f){for(var l=g+f;a.o<l;)k[k.length]=p.A(a);if(a.o!=l)throw"Content size is not correct for container starting at offset "+g;}else try{for(;;){l=p.A(a);if(0===
l.tag)break;k[k.length]=l}f=g-a.o}catch(m){throw"Exception while decoding undefined length content: "+m;}}else a.o+=f;return new p(b,e,f,d,k)};p.test=function(){for(var a=[{value:[39],ma:39},{value:[129,201],ma:201},{value:[131,254,220,186],ma:16702650}],c=0,b=a.length;c<b;++c){var d=p.$a(new q(a[c].value,0));d!=a[c].ma&&document.write("In test["+c+"] expected "+a[c].ma+" got "+d+"\n")}};p.prototype.u=function(){return this.wb().substr(2*this.pa,2*this.length)};v.prototype.gc=function(a){try{var c=
0,b=0,d=/^\s*(?:[0-9A-Fa-f][0-9A-Fa-f]\s*)+$/.test(a)?Y.A(a):H.Ea(a),f=p.A(d);if(9===f.sub.length){c=f.sub[1].u();this.B=w(c);b=f.sub[2].u();this.L=parseInt(b,16);var e=f.sub[3].u();this.G=w(e);var k=f.sub[4].u();this.i=w(k);var g=f.sub[5].u();this.j=w(g);var l=f.sub[6].u();this.$=w(l);var m=f.sub[7].u();this.aa=w(m);var n=f.sub[8].u();this.X=w(n)}else if(2===f.sub.length){var q=f.sub[1].sub[0],c=q.sub[0].u();this.B=w(c);b=q.sub[1].u();this.L=parseInt(b,16)}}catch(r){}};v.prototype.Mb=function(a){a=
a||{};return a.hasOwnProperty("n")&&a.hasOwnProperty("e")};v.prototype.Lb=function(a){a=a||{};return a.hasOwnProperty("n")&&a.hasOwnProperty("e")&&a.hasOwnProperty("d")&&a.hasOwnProperty("p")&&a.hasOwnProperty("q")&&a.hasOwnProperty("dmp1")&&a.hasOwnProperty("dmq1")&&a.hasOwnProperty("coeff")};v.prototype.ic=function(a){this.B=a.B;this.L=a.L;a.hasOwnProperty("d")&&(this.G=a.G,this.i=a.i,this.j=a.j,this.$=a.$,this.aa=a.aa,this.X=a.X)};F.prototype=new v;F.prototype.constructor=F;D.prototype.setKey=
function(a){this.log&&this.key&&console.warn("A key was already set, overriding existing.");this.key=new F(a)};D.prototype.getKey=function(a){if(!this.key){this.key=new F;if(a&&"[object Function]"==={}.toString.call(a)){this.key.Hb(this.ab,this.bb,a);return}this.key.Gb(this.ab,this.bb)}return this.key};v.prototype.encrypt256BitKey=function(a){if("string"!=typeof a||a instanceof String)throw Error("parameter is no string");if(64!=hey.length)throw Error("key length missmatch");var c=this.B.bitLength()+
7>>3;a=w(a);a=this.cb(a);if(null==a)return null;for(var b=a.toByteArray(),d=0;d<b.length&&0==b[d];)++d;if(b.length-d!=c-1||1!=b[d])return null;for(++d;0!=b[d];)if(++d>=b.length)return null;c="";for(d+=19;++d<b.length;)a=b[d],0>a&&(a=256+a),16>a&&(c+="0"),c+=a.toString(16);return c};v.prototype.verificationSign=function(a){var c=w(a);a=this.cb(c);if(null==a)return null;c=this.B.ka()+7>>3;a=a.zc();for(var b=0;b<a.length&&0==a[b];)++b;if(a.length-b!=c-1||1!=a[b])return null;for(++b;0!=a[b];)if(++b>=
a.length)return null;for(var d="",b=b+19;++b<a.length;)c=a[b],0>c&&(c=256+c),16>c&&(d+="0"),d+=c.toString(16);return d};D.prototype.verificationSign=function(a){try{return this.getKey().verificationSign(a)}catch(c){return!1}};v.prototype.parsePublicCert=function(a){try{var c=0,b=0,d=H.Ea(a),f=p.A(d);if(3!==f.sub.length)return!1;var e=p.A(f.sub[0].sub[6].sub[1].stream,!0).sub[0],c=e.sub[0].u();this.B=w(c);b=e.sub[1].u();this.L=parseInt(b,16);return!0}catch(k){return!1}};D.prototype.setPublicCert=function(a){this.key=
new v;"string"===typeof a&&this.key.parsePublicCert(a)};v.prototype.verifyPublicCertSign=function(a){try{var c=H.Ea(a),b=p.A(c);if(3!==b.sub.length)return!1;var d=CloudRailClient.Converter.ArrayBuffer.fromHex(b.sub[0].wb()),e=CloudRailClient.Converter.ArrayBuffer.toHex(CloudRailClient.Crypto.Hash.SHA256.hash(d)),h=b.sub[2].u().substr(2);return this.verificationSign(h)==e?!0:!1}catch(k){return!1}};D.prototype.verifyPublicCertSign=function(a){return this.key?this.key.verifyPublicCertSign(a):!1};Z.JSEncrypt=
D})(Q);var R=window,S=R.CloudRailClient||{};(S.Crypto=S.Crypto||{}).JSEncrypt=Q.JSEncrypt;R.hasOwnProperty("CloudRailClient")||(R.CloudRailClient=S);
